### ISSUE TITLE
Add support for MSG Contact file

### ISSUE THREAD

**Issue by gggfreak2003** [TeamMsgExtractor/msg-extractor#110]
I want to parse a contact msg-file but it handles it like a normal message and I only get the from, to, subject fields which are empty. Is there any way to parse a contact file with msg-extractor? 

I have seen that in properties.py there are values defined for a contact card. How could I use them?

Thanks in advanced for your help! This is a really cool lib!

**Comment by TheElementalOfCreation** [comment]
Hello! Sorry for taking so long to reply, but I am unfamiliar with this form of msg. as such, would you mind sending an example of this type (inside of a zip folder) to `arceusthe@gmail.com`? It would help us to start looking into how these msg files are structured and what we may be able to do in our code to detect them. 

Thank you for your time.

**Comment by gggfreak2003** [comment]
Thanks for your fast response. I have sended you an email with an example msg file.

**Comment by TheElementalOfCreation** [comment]
I have received the email with the MSG file. I will let you know when I have more information for you about this issue.

**Comment by TheElementalOfCreation** [comment]
I have now been able to identify most of the properties in the example contact file you have sent me. Work will soon be started on creating a new class to handle such files.

**Comment by TheElementalOfCreation** [comment]
This should now be implemented properly in the most recent versions.

**Comment by TheElementalOfDestruction** [comment]
Reopened this as I'm currently working on full support for contacts including saving. Next update has a few other things I am finishing up before it will be released (information is on the discord about the development) but the Contact class is now mostly ready.

There is only one feature not being added to this version that I want to add eventually which is the ability to generate the image for a contact's business card. 

Additionally, there is currently still an issue in the next version that causes the header to not inject properly into the RTF which frequently corrupts the body for a contact.

**Comment by TheElementalOfDestruction** [comment]
With the exception of business card generation, this was completed in 0.35.0. Let me know if you have any issues with it. I'm going to be closing it for now.
