### ISSUE TITLE
'cp949' codec can't decode bytes

### ISSUE THREAD

**Issue by ricardo-phantom** [TeamMsgExtractor/msg-extractor#111]
**Bug Metadata**
* - [x] Using latest supported version of extract_msg
* Your python version: Python [2.7]
* How did you launch extract_msg?
          I used the extract_msg package

**Describe the bug**
Extract msg module is unable to extract certain msg files. Fails with `UnicodeDecodeError: 'cp949' codec can't decode bytes in position 45-46: illegal multibyte sequence`

**What code did you use or can we use to reproduce this error?

My code:

```
import extract_msg
import os
from subprocess import Popen, PIPE

msg = extract_msg.Message("/Users/rmunoz/Downloads/hm.msg")
```

Is there a message.msg file you want to share to help us reproduce this?
- [x] Uploaded message 
[problematic_msg.zip](https://github.com/mattgwwalker/msg-extractor/files/4033062/problematic_msg.zip)

**Traceback**
```
Traceback (most recent call last):
  File "msg2.py", line 7, in <module>
    msg = extract_msg.Message("/Users/rmunoz/Downloads/hm.msg")
  File "/Library/Python/2.7/site-packages/extract_msg/message.py", line 95, in __init__
    self.body
  File "/Library/Python/2.7/site-packages/extract_msg/message.py", line 460, in body
    self._body = self._getStringStream('__substg1.0_1000')
  File "/Library/Python/2.7/site-packages/extract_msg/message.py", line 166, in _getStringStream
    return None if tmp is None else tmp.decode(self.stringEncoding)
UnicodeDecodeError: 'cp949' codec can't decode bytes in position 45-46: illegal multibyte sequence
```

**Comment by ricardo-phantom** [comment]
Something interesting to note is that the older version of the module **ExtractMsg-0.3-py2-none-any.whl**  is able to successfully extract the .msg file I attached to this issue.

**Comment by ricardo-phantom** [comment]
Hello,

Just wondering if your team has had a chance to look at this ticket or test out the problematic msg file I attached.

Thank you,
Ricardo

**Comment by TheElementalOfCreation** [comment]
Sorry for not responding. We are currently looking into the matter. We'll let you know when we have more information.

**Comment by ricardo-phantom** [comment]
No worries, thank you @TheElementalOfCreation !

**Comment by ricardo-phantom** [comment]
Hello @TheElementalOfCreation 

Please let me know the current status if possible, I would appreciate it. Thank you!

**Comment by leemengwei** [comment]
@TheElementalOfCreation Hello， are we good now with coding error like these?

**Comment by leemengwei** [comment]
> Something interesting to note is that the older version of the module **ExtractMsg-0.3** is able to successfully extract the .msg file I attached to this issue.

Hi, what do u mean: package 'ExtractMsg-0.3', I see the latest version of extract_msg is 0.22, is your mentioned ExtractMsg-0.3 refer to something else? thanks!

**Comment by TheElementalOfCreation** [comment]
In relation to this issue, we are finding that several codecs are not being properly interpreted from the values inside the msg files. We are currently still trying to figure out what the correct codecs are for these scenarios. Until then, we will be unable to fix this problem.

**Comment by leemengwei** [comment]
> In relation to this issue, we are finding that several codecs are not being properly interpreted from the values inside the msg files. We are currently still trying to figure out what the correct codecs are for these scenarios. Until then, we will be unable to fix this problem.

Thanks for your time! Solving that decoding problem really matters a lot to me! I'm sincerely looking forward for an update, take your time!

**Comment by TheElementalOfCreation** [comment]
@ricardo-phantom Could you open your outlook and check what encoding it is using for emails? Go to File > Options > Advanced and scroll down to "International Options" And tell me what it is set to for "Preferred encoding for outgoing messages"? I believe this may help me in determining what the encoding is that is being used for this email. Thank you.

**Comment by TheElementalOfDestruction** [comment]
@ricardo-phantom After finally tracking down a conversion of the code page numbers to actual encodings, it looks like the msg file you provided actually has the wrong encoding marked internally. So while a similar error is out fault, it seems that this specific encoding issue is that fault directly of whatever generated the msg file.

**Comment by TheElementalOfDestruction** [comment]
Apparently it looks like I forgot to update this. Support for several additional codecs was added, and proper mapping for values to codecs was added base on Microsoft's documentation. Like I said before, it seems like the file is incorrectly marked with an encoding. Now that you can manually swap the used encoding, I would say this issue should be closed.
