### ISSUE TITLE
Could not recognize msg class type "IPM.Schedule.Meeting.Request"

### ISSUE THREAD

**Issue by joanrodriguezr** [TeamMsgExtractor/msg-extractor#143]
**Bug Metadata**
* Version of extract_msg: [0.25.3]
* Your python version: Python [v3.7.0:1bf9cc5093]
* How did you launch extract_msg?
  - I used the extract_msg package within a .py file

**Describe the bug**
When processing a .msg file which has a  scheduled meeting request it provides me the following Exception message:
"Could not recognize msg class type "IPM.Schedule.Meeting.Request". It is recommended you report this to the developers."

Is there a message.msg file you want to share to help us reproduce this?
Due to company policy I can't add here the msg but the content is similar to this one:

**Traceback**

**Screenshots**

**Additional context**

**Comment by TheElementalOfDestruction** [comment]
We are currently already attempting to add this feature. To help us in doing so, can you please do a few things for us? 
1. Please update to the most recent version (0.26.2). One of our steps will simply not work because the feature has not been implemented in the version you are working with.  
2. Please show us the full exception that you got. If the traceback contains a line in the Attachment file, then your "IPM.Schedule.Meeting.Request" file is an attachment and will need to be extracted for our later steps. To do this, open Outlook and search for the attachment that does not have a standard message symbol. It may look different depending on your version of Outlook, but I believe it will look something like [this](https://imgur.com/a/Pl9VnEh). Once you have found the attachment, drag it into the file explorer that your os uses.
3. Once you have saved the specific file that is causing this issue, please open it using `msg = extract_msg.openMsg("path/to/msg", strict = False)`
4. Please tell us the results of calling `print(msg.slistDir(True, True))` and `print(msg.named.namedProperties)`. Rest assured, neither of these will actually return any of the data contained inside of the streams, only a list of what streams exist (so we can get a better idea on what will actually need to be parsed) and a list of all the identifiers for the named properties (again, not the data they contain and, again, so we can get a better idea of what will actually need to be parsed.

Thank you for your time.

**Comment by joanrodriguezr** [comment]
Step 1: Completed. Upgraded to 0.26.3
Step 2: I don't know if I'm doing sometthing wrong but the traceback I get is the same "Could not recognize msg class type "IPM.Schedule.Meeting.Request". It is recommended you report this to the developers." Is is valuable for you to show the contents of the message provoking the exception? Attached Captura file, I can't see the image you say:

![Captura](https://user-images.githubusercontent.com/14201057/90151698-4b304700-dd87-11ea-9b66-34fac9452280.JPG)

Step3:  Executed
Step4: Here you have the results:

['__attach_version1.0_#00000000', '__attach_version1.0_#00000000/__properties_version1.0', '__attach_version1.0_#00000000/__substg1.0_0FF90102', '__attach_version1.0_#00000000/__substg1.0_3001001E', '__attach_version1.0_#00000000/__substg1.0_37010102', '__attach_version1.0_#00000000/__substg1.0_3703001E', '__attach_version1.0_#00000000/__substg1.0_3704001E', '__attach_version1.0_#00000000/__substg1.0_3707001E', '__attach_version1.0_#00000000/__substg1.0_370E001E', '__attach_version1.0_#00000000/__substg1.0_3712001E', '__attach_version1.0_#00000000/__substg1.0_371D0102', '__attach_version1.0_#00000000/__substg1.0_3A0C001E', '__attach_version1.0_#00000000/__substg1.0_8088001E', '__nameid_version1.0', '__nameid_version1.0/__substg1.0_00020102', '__nameid_version1.0/__substg1.0_00030102', '__nameid_version1.0/__substg1.0_00040102', '__nameid_version1.0/__substg1.0_10000102', '__nameid_version1.0/__substg1.0_10010102', '__nameid_version1.0/__substg1.0_10020102', '__nameid_version1.0/__substg1.0_10030102', '__nameid_version1.0/__substg1.0_10040102', '__nameid_version1.0/__substg1.0_10050102', '__nameid_version1.0/__substg1.0_10060102', '__nameid_version1.0/__substg1.0_10070102', '__nameid_version1.0/__substg1.0_10080102', '__nameid_version1.0/__substg1.0_10090102', '__nameid_version1.0/__substg1.0_100A0102', '__nameid_version1.0/__substg1.0_100B0102', '__nameid_version1.0/__substg1.0_100C0102', '__nameid_version1.0/__substg1.0_100D0102', '__nameid_version1.0/__substg1.0_100E0102', '__nameid_version1.0/__substg1.0_100F0102', '__nameid_version1.0/__substg1.0_10100102', '__nameid_version1.0/__substg1.0_10110102', '__nameid_version1.0/__substg1.0_10120102', '__nameid_version1.0/__substg1.0_10130102', '__nameid_version1.0/__substg1.0_10140102', '__nameid_version1.0/__substg1.0_10150102', '__nameid_version1.0/__substg1.0_10160102', '__nameid_version1.0/__substg1.0_10170102', '__nameid_version1.0/__substg1.0_10180102', '__nameid_version1.0/__substg1.0_10190102', '__nameid_version1.0/__substg1.0_101A0102', '__nameid_version1.0/__substg1.0_101B0102', '__nameid_version1.0/__substg1.0_101C0102', '__nameid_version1.0/__substg1.0_101D0102', '__nameid_version1.0/__substg1.0_101E0102', '__properties_version1.0', '__recip_version1.0_#00000000', '__recip_version1.0_#00000000/__properties_version1.0', '__recip_version1.0_#00000000/__substg1.0_0C240102', '__recip_version1.0_#00000000/__substg1.0_0FF60102', '__recip_version1.0_#00000000/__substg1.0_0FF90102', '__recip_version1.0_#00000000/__substg1.0_0FFF0102', '__recip_version1.0_#00000000/__substg1.0_3001001E', '__recip_version1.0_#00000000/__substg1.0_3002001E', '__recip_version1.0_#00000000/__substg1.0_3003001E', '__recip_version1.0_#00000000/__substg1.0_300B0102', '__recip_version1.0_#00000000/__substg1.0_39FE001E', '__recip_version1.0_#00000000/__substg1.0_3A20001E', '__recip_version1.0_#00000000/__substg1.0_3A76001E', '__recip_version1.0_#00000000/__substg1.0_3A77001E', '__recip_version1.0_#00000000/__substg1.0_5FE5001E', '__recip_version1.0_#00000000/__substg1.0_5FF70102', '__substg1.0_001A001E', '__substg1.0_0037001E', '__substg1.0_003B0102', '__substg1.0_003D001E', '__substg1.0_003F0102', '__substg1.0_0040001E', '__substg1.0_00410102', '__substg1.0_0042001E', '__substg1.0_00430102', '__substg1.0_0044001E', '__substg1.0_004F0102', '__substg1.0_0050001E', '__substg1.0_00510102', '__substg1.0_00520102', '__substg1.0_0064001E', '__substg1.0_0065001E', '__substg1.0_0070001E', '__substg1.0_00710102', '__substg1.0_0075001E', '__substg1.0_0076001E', '__substg1.0_0077001E', '__substg1.0_0078001E', '__substg1.0_007D001E', '__substg1.0_0C190102', '__substg1.0_0C1A001E', '__substg1.0_0C1D0102', '__substg1.0_0C1E001E', '__substg1.0_0C1F001E', '__substg1.0_0E02001E', '__substg1.0_0E03001E', '__substg1.0_0E04001E', '__substg1.0_0E1D001E', '__substg1.0_0E4C0102', '__substg1.0_0E590102', '__substg1.0_0F030102', '__substg1.0_1000001E', '__substg1.0_10090102', '__substg1.0_1013001E', '__substg1.0_1015001E', '__substg1.0_1035001E', '__substg1.0_300B0102', '__substg1.0_30140102', '__substg1.0_3A76001E', '__substg1.0_3A77001E', '__substg1.0_4022001E', '__substg1.0_4023001E', '__substg1.0_4024001E', '__substg1.0_4025001E', '__substg1.0_4030001E', '__substg1.0_4031001E', '__substg1.0_4034001E', '__substg1.0_4035001E', '__substg1.0_4038001E', '__substg1.0_4039001E', '__substg1.0_5D01001E', '__substg1.0_5D02001E', '__substg1.0_5D07001E', '__substg1.0_5D08001E', '__substg1.0_5D0A001E', '__substg1.0_5D0B001E', '__substg1.0_800A001E', '__substg1.0_800E0102', '__substg1.0_80120102', '__substg1.0_80130102', '__substg1.0_8014001E', '__substg1.0_80160102', '__substg1.0_8017001E', '__substg1.0_8019001E', '__substg1.0_801A0102', '__substg1.0_801B001E', '__substg1.0_8020001E', '__substg1.0_8021001E', '__substg1.0_8024001E', '__substg1.0_80270048', '__substg1.0_8028101E', '__substg1.0_8028101E-00000000', '__substg1.0_8028101E-00000001', '__substg1.0_8028101E-00000002', '__substg1.0_802B101E', '__substg1.0_802B101E-00000000', '__substg1.0_802B101E-00000001', '__substg1.0_802B101E-00000002', '__substg1.0_802B101E-00000003', '__substg1.0_802B101E-00000004', '__substg1.0_802B101E-00000005', '__substg1.0_802B101E-00000006', '__substg1.0_802B101E-00000007', '__substg1.0_802B101E-00000008', '__substg1.0_802B101E-00000009', '__substg1.0_802B101E-0000000A', '__substg1.0_802B101E-0000000B', '__substg1.0_802B101E-0000000C', '__substg1.0_802B101E-0000000D', '__substg1.0_802B101E-0000000E', '__substg1.0_802B101E-0000000F', '__substg1.0_802B101E-00000010', '__substg1.0_802B101E-00000011', '__substg1.0_802B101E-00000012', '__substg1.0_802B101E-00000013', '__substg1.0_802C0102', '__substg1.0_802D001E', '__substg1.0_802E0102', '__substg1.0_8030001E', '__substg1.0_8031001E', '__substg1.0_8032001E', '__substg1.0_8033001E', '__substg1.0_8034001E', '__substg1.0_8035001E', '__substg1.0_8036001E', '__substg1.0_8037001E', '__substg1.0_8038001E', '__substg1.0_8039001E', '__substg1.0_803A001E', '__substg1.0_803B0102', '__substg1.0_803C001E', '__substg1.0_803D001E', '__substg1.0_803E001E', '__substg1.0_803F001E', '__substg1.0_8040001E', '__substg1.0_8041001E', '__substg1.0_8043001E', '__substg1.0_8044001E', '__substg1.0_8045001E', '__substg1.0_8046001E', '__substg1.0_8047001E', '__substg1.0_80490102', '__substg1.0_804A001E', '__substg1.0_804C0102', '__substg1.0_804D0102', '__substg1.0_804E0102', '__substg1.0_804F001E', '__substg1.0_8050001E', '__substg1.0_8051001E', '__substg1.0_8054001E', '__substg1.0_8055001E', '__substg1.0_8056001E', '__substg1.0_80571003', '__substg1.0_8058101E', '__substg1.0_8058101E-00000000', '__substg1.0_805A001E', '__substg1.0_805B0102', '__substg1.0_805E001E', '__substg1.0_805F0048', '__substg1.0_8061001E', '__substg1.0_8063001E', '__substg1.0_8065001E', '__substg1.0_8066001E', '__substg1.0_8067001E', '__substg1.0_8068001E', '__substg1.0_8069001E', '__substg1.0_806A001E', '__substg1.0_806B001E', '__substg1.0_806C001E', '__substg1.0_806D001E', '__substg1.0_806E001E', '__substg1.0_806F001E', '__substg1.0_8070001E', '__substg1.0_8072101E', '__substg1.0_8072101E-00000000', '__substg1.0_8072101E-00000001', '__substg1.0_8072101E-00000002', '__substg1.0_8072101E-00000003', '__substg1.0_8072101E-00000004', '__substg1.0_8073001E', '__substg1.0_8074001E', '__substg1.0_8075001E', '__substg1.0_8076001E', '__substg1.0_8077001E', '__substg1.0_8078001E', '__substg1.0_8079001E', '__substg1.0_807A001E', '__substg1.0_807B001E', '__substg1.0_807C001E', '__substg1.0_807D001E', '__substg1.0_807E001E', '__substg1.0_807F001E', '__substg1.0_8080101E', '__substg1.0_8080101E-00000000', '__substg1.0_8080101E-00000001', '__substg1.0_8080101E-00000002', '__substg1.0_8080101E-00000003', '__substg1.0_8080101E-00000004', '__substg1.0_8080101E-00000005', '__substg1.0_8081001E', '__substg1.0_8082001E', '__substg1.0_8083001E', '__substg1.0_8084001E', '__substg1.0_80851003', '__substg1.0_8086001E', '__substg1.0_8087001E']

{'8205': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D1D0>, '8223': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D240>, '820D': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D2B0>, '820E': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D320>, '8235': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D390>, '8236': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D400>, '8514': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D470>, '8552': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D4E0>, '8502': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D550>, '8503': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D5C0>, '8208': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D630>, '8215': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D6A0>, '8217': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D710>, '8229': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D780>, '0003': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D7F0>, '8501': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D860>, '8560': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D8D0>, '8224': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D940>, '825E': <extract_msg.named.NumericalNamedProperty object at 0x000002492189D9B0>, '825F': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DA20>, '8238': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DA90>, '8204': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DB00>, '825D': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DB70>, '8554': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DBE0>, '8506': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DC50>, '0002': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DCC0>, '0023': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DD30>, '0024': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DDA0>, '0005': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DE10>, '000A': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DE80>, '001A': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DEF0>, '0026': <extract_msg.named.NumericalNamedProperty object at 0x000002492189DF60>, 'urn:schemas:calendar:transparent': <extract_msg.named.StringNamedProperty object at 0x000002492189DFD0>, 'x-ms-exchange-organization-authas': <extract_msg.named.StringNamedProperty object at 0x000002492189C080>, '0001': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C0F0>, 'XmlExtractedUrls': <extract_msg.named.StringNamedProperty object at 0x000002492189C160>, 'IsPartiallyIndexed': <extract_msg.named.StringNamedProperty object at 0x000002492189C1D0>, 'LastIndexingAttemptTime': <extract_msg.named.StringNamedProperty object at 0x000002492189C240>, 'BigFunnelCorrelationId': <extract_msg.named.StringNamedProperty object at 0x000002492189C2B0>, 'ExtensionsList': <extract_msg.named.StringNamedProperty object at 0x000002492189C320>, '0016': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C390>, '0009': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C400>, 'EntityNames': <extract_msg.named.StringNamedProperty object at 0x000002492189C470>, '0006': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C4E0>, '0007': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C550>, '0008': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C5C0>, '000B': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C630>, '000C': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C6A0>, '000D': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C710>, '000E': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C780>, '000F': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C7F0>, '0010': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C860>, '0011': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C8D0>, '0012': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C940>, '0013': <extract_msg.named.NumericalNamedProperty object at 0x000002492189C9B0>, '0014': <extract_msg.named.NumericalNamedProperty object at 0x000002492189CA20>, '0017': <extract_msg.named.NumericalNamedProperty object at 0x000002492189CA90>, 'Locations': <extract_msg.named.StringNamedProperty object at 0x000002492189CB00>, 'DetectedLanguage': <extract_msg.named.StringNamedProperty object at 0x000002492189CB70>, 'IOpenTypedFacet.EventLocations': <extract_msg.named.StringNamedProperty object at 0x000002492189CBE0>, 'EntityExtraction/KeyPhraseExtraction2.0': <extract_msg.named.StringNamedProperty object at 0x000002492189CC50>, 'EntityExtractionServiceDiagnosticContext': <extract_msg.named.StringNamedProperty object at 0x000002492189CCC0>, 'TeeVersion': <extract_msg.named.StringNamedProperty object at 0x000002492189CD30>, 'EntityExtractionSuccess': <extract_msg.named.StringNamedProperty object at 0x000002492189CDA0>, 'EntityExtraction/ExtractLanguage1.0': <extract_msg.named.StringNamedProperty object at 0x000002492189CE10>, 'EntityExtraction/SubjectTermFrequency1.0': <extract_msg.named.StringNamedProperty object at 0x000002492189CE80>, 'EntityExtraction/TermFrequency1.0': <extract_msg.named.StringNamedProperty object at 0x000002492189CEF0>, 'EntityExtraction/Url1.0': <extract_msg.named.StringNamedProperty object at 0x000002492189CF60>, 'EntityExtraction/EmbeddedUrl1.0': <extract_msg.named.StringNamedProperty object at 0x000002492189CFD0>, 'GraphNodeVersion': <extract_msg.named.StringNamedProperty object at 0x00000249218A5080>, 'GraphNodeId': <extract_msg.named.StringNamedProperty object at 0x00000249218A50F0>, 'GraphNodeType': <extract_msg.named.StringNamedProperty object at 0x00000249218A5160>, 'IsSecondaryCopy': <extract_msg.named.StringNamedProperty object at 0x00000249218A51D0>, 'GraphNodeCompactAcl': <extract_msg.named.StringNamedProperty object at 0x00000249218A5240>, 'GraphNodeAclHashCode': <extract_msg.named.StringNamedProperty object at 0x00000249218A52B0>, 'GraphNodeSmallAcl': <extract_msg.named.StringNamedProperty object at 0x00000249218A5320>, 'EntityExtraction/M2HClassifier1.0': <extract_msg.named.StringNamedProperty object at 0x00000249218A5390>, 'ConversationIndexTrackingEx': <extract_msg.named.StringNamedProperty object at 0x00000249218A5400>, 'x-ms-exchange-organization-authsource': <extract_msg.named.StringNamedProperty object at 0x00000249218A5470>, 'IsSigned': <extract_msg.named.StringNamedProperty object at 0x00000249218A54E0>, 'IsReadReceipt': <extract_msg.named.StringNamedProperty object at 0x00000249218A5550>, 'received-spf': <extract_msg.named.StringNamedProperty object at 0x00000249218A55C0>, 'x-ms-exchange-organization-originalclientipaddress': <extract_msg.named.StringNamedProperty object at 0x00000249218A5630>, 'x-ms-exchange-organization-originalserveripaddress': <extract_msg.named.StringNamedProperty object at 0x00000249218A56A0>, '232A': <extract_msg.named.NumericalNamedProperty object at 0x00000249218A5710>, 'Hashtags': <extract_msg.named.StringNamedProperty object at 0x00000249218A5780>, 'ExchangeApplicationFlags': <extract_msg.named.StringNamedProperty object at 0x00000249218A57F0>, 'ClientInfo': <extract_msg.named.StringNamedProperty object at 0x00000249218A5860>, 'HeaderBodyFragmentList': <extract_msg.named.StringNamedProperty object at 0x00000249218A58D0>, 'HasQuotedText': <extract_msg.named.StringNamedProperty object at 0x00000249218A5940>, 'IsQuotedTextChanged': <extract_msg.named.StringNamedProperty object at 0x00000249218A59B0>, 'x-ms-exchange-organization-submissionquotaskipped': <extract_msg.named.StringNamedProperty object at 0x00000249218A5A20>, 'NetworkMessageId': <extract_msg.named.StringNamedProperty object at 0x00000249218A5A90>, 'CurrentMessageSafetyFlags': <extract_msg.named.StringNamedProperty object at 0x00000249218A5B00>, 'EntityDocument': <extract_msg.named.StringNamedProperty object at 0x00000249218A5B70>, 'LatestMessageWordCount': <extract_msg.named.StringNamedProperty object at 0x00000249218A5BE0>, 'EntityExtractionServiceDiagnosticContextDelayed': <extract_msg.named.StringNamedProperty object at 0x00000249218A5C50>, 'EntityExtractionSuccessDelayed': <extract_msg.named.StringNamedProperty object at 0x00000249218A5CC0>, 'X-Microsoft-Antispam-Message-Info': <extract_msg.named.StringNamedProperty object at 0x00000249218A5D30>, 'TeeNextPayload': <extract_msg.named.StringNamedProperty object at 0x00000249218A5DA0>, 'TeeNextScenario': <extract_msg.named.StringNamedProperty object at 0x00000249218A5E10>, 'X-Microsoft-Antispam-Mailbox-Delivery': <extract_msg.named.StringNamedProperty object at 0x00000249218A5E80>, 'EntityExtraction/IRankerScoreDev1.0': <extract_msg.named.StringNamedProperty object at 0x00000249218A5EF0>, 'EntityExtraction/IRankerScore1.0': <extract_msg.named.StringNamedProperty object at 0x00000249218A5F60>, 'x-ms-publictraffictype': <extract_msg.named.StringNamedProperty object at 0x00000249218A5FD0>, 'ExplicitMessageCard': <extract_msg.named.StringNamedProperty object at 0x00000249218AD080>, 'IOpenTypedFacet.Com.Microsoft.Graph.MessageCard': <extract_msg.named.StringNamedProperty object at 0x00000249218AD0F0>, 'EntityExtraction/DomainClassifier1.0': <extract_msg.named.StringNamedProperty object at 0x00000249218AD160>, 'HashtagsEx': <extract_msg.named.StringNamedProperty object at 0x00000249218AD1D0>, 'EntityExtraction/CreativeWork1.0': <extract_msg.named.StringNamedProperty object at 0x00000249218AD240>, 'ItemCurrentFolderReason': <extract_msg.named.StringNamedProperty object at 0x00000249218AD2B0>, 'KeyPhrases': <extract_msg.named.StringNamedProperty object at 0x00000249218AD320>, 'x-ms-traffictypediagnostic': <extract_msg.named.StringNamedProperty object at 0x00000249218AD390>, 'x-ms-oob-tlc-oobclassifiers': <extract_msg.named.StringNamedProperty object at 0x00000249218AD400>, 'x-microsoft-antispam': <extract_msg.named.StringNamedProperty object at 0x00000249218AD470>, 'x-forefront-antispam-report': <extract_msg.named.StringNamedProperty object at 0x00000249218AD4E0>, 'x-ms-exchange-crosstenant-originalarrivaltime': <extract_msg.named.StringNamedProperty object at 0x00000249218AD550>, 'x-ms-exchange-crosstenant-fromentityheader': <extract_msg.named.StringNamedProperty object at 0x00000249218AD5C0>, 'x-ms-exchange-crosstenant-authsource': <extract_msg.named.StringNamedProperty object at 0x00000249218AD630>, 'x-ms-exchange-crosstenant-authas': <extract_msg.named.StringNamedProperty object at 0x00000249218AD6A0>, 'x-ms-exchange-crosstenant-network-message-id': <extract_msg.named.StringNamedProperty object at 0x00000249218AD710>, 'x-ms-exchange-transport-crosstenantheadersstamped': <extract_msg.named.StringNamedProperty object at 0x00000249218AD780>, 'authentication-results': <extract_msg.named.StringNamedProperty object at 0x00000249218AD7F0>, 'x-ms-office365-filtering-correlation-id': <extract_msg.named.StringNamedProperty object at 0x00000249218AD860>, 'x-ms-exchange-crosstenant-id': <extract_msg.named.StringNamedProperty object at 0x00000249218AD8D0>, 'EntityNamesDelayed': <extract_msg.named.StringNamedProperty object at 0x00000249218AD940>, 'x-ms-exchange-transport-endtoendlatency': <extract_msg.named.StringNamedProperty object at 0x00000249218AD9B0>, 'x-ms-exchange-processed-by-bccfoldering': <extract_msg.named.StringNamedProperty object at 0x00000249218ADA20>, 'x-header-trust': <extract_msg.named.StringNamedProperty object at 0x00000249218ADA90>, 'x-eopattributedmessage': <extract_msg.named.StringNamedProperty object at 0x00000249218ADB00>, 'KPRelevanceScoresInt32': <extract_msg.named.StringNamedProperty object at 0x00000249218ADB70>, '8580': <extract_msg.named.NumericalNamedProperty object at 0x00000249218ADBE0>, '8581': <extract_msg.named.NumericalNamedProperty object at 0x00000249218ADC50>, 'DocumentProcessingCorrelationId': <extract_msg.named.StringNamedProperty object at 0x00000249218ADCC0>}


Please let me know if I can help with anything else. Thanks in advance!

**Comment by gregoryfoster** [comment]
+1, I've also encountered this issue.

Here's an example `.msg` file containing a meeting request:
[RE  Industry WexEx (3).msg.zip](https://github.com/mattgwwalker/msg-extractor/files/5099315/RE.Industry.WexEx.3.msg.zip)

Here's the default traceback if that's helpful, let me know if you'd like additional detail.

```bash
Traceback (most recent call last):
  File ".venv/lib/python3.8/site-packages/extract_msg/message.py", line 301, in attachments
    return self._attachments
AttributeError: 'Message' object has no attribute '_attachments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process.py", line 436, in <module>
    process()
  File ".venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "process.py", line 329, in email
    msg = extract_msg.openMsg(current_filename)
  File ".venv/lib/python3.8/site-packages/extract_msg/utils.py", line 293, in openMsg
    return Message(path, prefix, attachmentClass, filename, delayAttachments)
  File ".venv/lib/python3.8/site-packages/extract_msg/message.py", line 52, in __init__
    self.attachments
  File ".venv/lib/python3.8/site-packages/extract_msg/message.py", line 314, in attachments
    self._attachments.append(self.attachmentClass(self, attachmentDir))
  File ".venv/lib/python3.8/site-packages/extract_msg/attachment.py", line 47, in __init__
    self.__data = openMsg(self.msg.path, self.__prefix, self.__class__)
  File ".venv/lib/python3.8/site-packages/extract_msg/utils.py", line 295, in openMsg
    raise UnrecognizedMSGTypeError('Could not recognize msg class type "{}". It is recommended you report this to the developers.'.format(msg.classType))
extract_msg.exceptions.UnrecognizedMSGTypeError: Could not recognize msg class type "IPM.Schedule.Meeting.Request". It is recommended you report this to the developers.
```

**Comment by TheElementalOfDestruction** [comment]
The module can now properly open and read appointment and meeting files.

**Comment by TheElementalOfDestruction** [comment]
Completed in 0.35.0. Let me know if you have any issues with it.
