### ISSUE TITLE
Version tzlocal pinned to 1.5.1, but I need to use 2.1

### ISSUE THREAD

**Issue by dickkniep** [TeamMsgExtractor/msg-extractor#155]
The tzlocal version is pinned, to 1.5.1 However I have another dependence in a project to use 2.1

I have tested the version 2.1 agains msg-extractor and it does not seem to differ. So I would kindly request you to modify the requirements.txt to:

`tzlocal~=1.5.1`

Cheers.

**Comment by TheElementalOfDestruction** [comment]
You should be good in the newest version of the module now.
