### ISSUE TITLE
Dump the message text instead of extracting

### ISSUE THREAD

**Issue by alper** [TeamMsgExtractor/msg-extractor#161]
Would it be at all possible to have a flag that let's me just dump the message text to stdout instead of creating a folder etc.?

**Comment by TheElementalOfDestruction** [comment]
For the command line, yes?

**Comment by zeroepoch** [comment]
Somewhat related to this request, the pip package doesn't install a script in the bin directory. I have to use `python3 -m extract_msg` to run the main script.

**Comment by TheElementalOfDestruction** [comment]
@zeroepoch please open a new feature request. Talk of that will occur there.

**Comment by zeroepoch** [comment]
Sorry, I created #162 now rather than hijacking or adding to this bug.

**Comment by TheElementalOfDestruction** [comment]
This should be working now; you can now use the command line switch `--dump-stdout` to dump the message text to the command line. If you want it to do it in a different way (you were not very specific) then let me know and I will do what I can.
