### ISSUE TITLE
Saving file attachments

### ISSUE THREAD

**Issue by mfgopspro** [TeamMsgExtractor/msg-extractor#164]
Guys, this is useful code and i have NO BUG, just a question.

I see you have as a TO DO to add functions to allow saving attachments to a custom location. My use case is saving attachments to S3 buckets on AWS via a Lambda function.

Do you have use case on AWS?

Where do you stand on the new save function?

Thank you.

**Comment by TheElementalOfDestruction** [comment]
Currently I am the only one working on the code, so I'll answer this question as best I can:

I have no idea what AWS is or how to even use it. When you refer to the "new save function" do you mean the one that will allow custom locations?

I will say that I am planning to rewrite a good portion of the save functions to move away from using the os module as much as possible (it's not very thread safe), and I have been meaning to make an issue about that.

**Comment by mfgopspro** [comment]
Hi Destiny I appreciate your quick reply.

AWS is Amazon Web services which is a hugely popular data platform in the
cloud.

 Yes I was referring to adding ability to specify the output location when
saving message attachments.

This could be some operating system location or in my use case a file
storage location  on the AWS platform.  I don’t think you would have to
create special code just for AWS.

 Sounds like for now I need to seek other options but I will keep an eye
out on your progress thank you.

**Comment by TheElementalOfDestruction** [comment]
Honestly, I'm pretty fast when it comes to things like this. I can probably write the functionality within the month, if not sooner. I'll let you know. For now you can follow [this](https://github.com/TeamMsgExtractor/msg-extractor/issues/165) issue for full details on the progress.

**Comment by Yoyoma22** [comment]
To save on AWS, we probably would need a new function, but i would not suggest to convolute this library with another library. 
When we fix saving in a custom location, you could save to a temporary directory and then pick up the file for AWS transfer (you can even use the examples online for this).

**Comment by TheElementalOfDestruction** [comment]
Saving to custom locations should be working, and I'm no longer sure if this issue should remain open. I'll be closing it for now but if we need we can reopen it.
