### ISSUE TITLE
The ability to easily save files with a custom file name at a custom location.

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [TeamMsgExtractor/msg-extractor#165]
Add the ability to easily save msg files and their content to a custom location. In addition, the os code should be replaced with paths that are passed down to the attachments to hopefully allow the module to work in threaded environments.

**Comment by x1mus** [comment]
Hello !
Do you have any news on when this functionnality will be implemented ? ^

**Comment by TheElementalOfDestruction** [comment]
This is tentatively planned for the next major version. I've been trying to focus on making sure the existing code isn't broken and that everything we already should have works before I try to go and redo it so I have a good place to be able to fall back on. Basically all of the saving code currently uses os to save things where we want them which is not the best way to be doing it.

**Comment by x1mus** [comment]
Thanks for the response !
Looking forward to it since i'm trying to integrate it as an AssemblyLine service :)

**Comment by TheElementalOfDestruction** [comment]
This should now be implemented @x1mus.
