### ISSUE TITLE
Special Character Appearance \\~

### ISSUE THREAD

**Issue by frndadi** [TeamMsgExtractor/msg-extractor#167]
When I am trying to parse the .msg file, compressedRtf which is a class property in MessageBase class it returns special character the in text.  Its not that it only appears on new line "\n" but also in the middle of line. Some of the encoding are also getting converted as well.

![image](https://user-images.githubusercontent.com/75553319/101270250-4875b980-379d-11eb-81c5-c4247dd8b2ed.png)

![image](https://user-images.githubusercontent.com/75553319/101270348-16188c00-379e-11eb-9908-ec8d907f26e7.png)

Thanks!

**Comment by TheElementalOfDestruction** [comment]
First, `compressedRtf` is a *compressed* stream, meaning that if you are seeing any weird characters in it that would be normal. However, if you have decompressed the stream that is a different story. A decompressed version can be directly accessed with `rtfBody`. 

If what you are showing is part of the decompressed stream, it looks like you are trying to view the RTF stream as if it were plain text, if I had to guess. My recommendation is to try saving it to a .rtf file and opening it with something that can read them. If you have opened the file in something that is supposed to be able to read RTF files, then I can think of a few things that might be going on:
1. `compressedRtf` is an unchanged stream, meaning we don't touch it at all when we extract it. As such, there might have been a problem with whatever created it and you are starting to see it now.
2. `rtfBody` uses an external module to decompress the stream: [compress_rtf](https://github.com/delimitry/compressed_rtf). If you used this property or this module, it may indicate that it had a problem with your compressed stream and you should contact them.
3. Whatever program you have used to read the RTF file may not be up to specification, leading to weird issues with your file. If the program was produced by Microsoft, then, while possible, this is unlikely.

However, without having access to the original file and/or compressed stream, I am very limited in the help I can provide.

**Comment by frndadi** [comment]
I agree compressedRtf  is a compressed stream, thus it contains weird character I was looking it as the same character was populating on my UI, I was wondering if my browser is causing this character thus started looking in backward direction and concluded compressedRTF itself is giving that character. As suggested above I tried using rtfbody as well then I look closely on notepad++.  It also contains same character(~).  However, when I look body it is clean and does not have any issue. But I need to either rtfbody or compressedRtf  as I need to convert them in HTML.

**Comment by TheElementalOfDestruction** [comment]
I'm unsure if your problem has been fixed from what you are saying. If it has not been fixed, again I must reiterate that this module has no effect on the data in `compressedRtf` or `rtfBody`. The first is unchanged and the second is generated by somebody else's module. And without direct access to the msg file that is causing this, I cannot provide you with much information.

As or converting to html, I would like to point you towards two things. The first is that you can check if the msg file already has html by checking the `htmlBody` property. The second is that msg files often have html encapsulated inside of the RTF body of the email, and you can use some programs to extract this. The one I personally use is [rtf-stream-parser](https://github.com/mazira/rtf-stream-parser), although I am working on porting that to Python.

As for direct conversion of RTF tags into HTML tags, I cannot currently recommend any Python modules as all of them I have tried have failed a specific test I created of valid RTF tags. Mind you, the test is meant to check if the module can handle what would essentially be a worst case scenario, but the test I give them is a perfectly valid one. I've attached a zip file containing my test file to this message. If the parser works correctly, every line in the file should look exactly the same.

[Document.zip](https://github.com/TeamMsgExtractor/msg-extractor/files/5654907/Document.zip)
