### ISSUE TITLE
A typo in attachment.py is causing it to crash

### ISSUE THREAD

**Issue by z3r0privacy** [TeamMsgExtractor/msg-extractor#181]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Version of extract_msg: 0.28.0
* Your python version: Python 3.8.7
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**

The package extract_msg crashes in module `attachment` class `Attachment` on line 44 https://github.com/TeamMsgExtractor/msg-extractor/blob/1de3677e9a542105238d57a2976b7d23c856207f/extract_msg/attachment.py#L44 when trying to open a message wit a `afByWebReference` attachment. Accessing `self.__props[37050003].value` is causing an `AttributeError`. Removing the `__` seems to fix the problem.

**What code did you use or can we use to reproduce this error?**

```python
import sys
import traceback
from extract_msg import Message, constants

try:
    m1 = Message("/home/myuser/test_mail/mail_w_webattachment.msg", attachmentErrorBehavior=constants.ATTACHMENT_ERROR_NOT_IMPLEMENTED)
    print (m1.to)
except Exception:
    traceback.print_exception(*sys.exc_info())
```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]
- [x] The message is confidential, but I could produce one.

**Traceback**
```
Traceback (most recent call last):
  File "/home/myuser/dev/msgextract_test/msg-extractor-master/extract_msg/message_base.py", line 142, in attachments
    return self._attachments
AttributeError: 'Message' object has no attribute '_attachments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myuser/dev/msgextract_test/msg-extractor-master/playground.py", line 6, in <module>
    m1 = Message("/home/myuser/test_mail/mail_w_webattachment.msg", attachmentErrorBehavior=constants.ATTACHMENT_ERROR_NOT_IMPLEMENTED)
  File "/home/myuser/dev/msgextract_test/msg-extractor-master/extract_msg/message.py", line 28, in __init__
    MessageBase.__init__(self, path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior)
  File "/home/myuser/dev/msgextract_test/msg-extractor-master/extract_msg/message_base.py", line 56, in __init__
    self.attachments
  File "/home/myuser/dev/msgextract_test/msg-extractor-master/extract_msg/message_base.py", line 156, in attachments
    self._attachments.append(self.attachmentClass(self, attachmentDir))
  File "/home/myuser/dev/msgextract_test/msg-extractor-master/extract_msg/attachment.py", line 44, in __init__
    elif (self.__props['37050003'].value & 0x7) == 0x7:
AttributeError: 'Attachment' object has no attribute '_Attachment__props'

```

**Screenshots**

_None_

**Additional context**

_None_

**Comment by TheElementalOfDestruction** [comment]
Ack, I knew I would miss one of them. Some of the stuff from Attachment got moved into a base class, so stuff like this was bound to happen. Give me a few minutes and I'll put out a fix.

**Comment by TheElementalOfDestruction** [comment]
Unfortunately, if you are getting to that point you are likely about to either get a `NotImplementedError` or a `TypeError` anyways.

**Comment by TheElementalOfDestruction** [comment]
I think I found all the problems and fixed them in the newest release. Let me know if 0.28.1 still has issues.

**Comment by z3r0privacy** [comment]
I've just tested it. Looks like everything is fine, all tests have passed, thank you!
The `NotImplementedError` is not that bad since it rarely happens and thanks to the new `UnsupportedAttachment` class the handling is even easier.
