### ISSUE TITLE
Saving an attachment to a custom location does not work.

### ISSUE THREAD

**Issue by Yoyoma22** [TeamMsgExtractor/msg-extractor#191]
**Bug Metadata**
* Version of extract_msg: 0.28.5
* Your python version: Python 3.9
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
When passing a custom path to the attachment save function, the full path is concatenated as a filename (removing file separators) and saved in the current directory (and not where we require the file to be saved).

[put your code here]
`savedAttFile = att.save(customPath=customPath, customFilename=longName, useFileName=True)`

Where 'att' is the returned attachment, 'customPath' is a fully qualified str(WindowsPath) object having a path like c:\temp\savedattachments and customFileName is actually the long name you returned 'anAttachment.pdf' for example.  I threw in 'useFileName' to true since i didn't know what that was doing.

In this example, 'savedAttFile' is a string that would look like ctempsavedattachmentsaattachment.pdf
the regex in prepareFile seems faulty, what is that function supposed to do?

Is there a message.msg file you want to share to help us reproduce this?
- None needed

**Traceback**
No traceback, fails silently.

**Screenshots**
![image](https://user-images.githubusercontent.com/74927546/109040284-bd210b80-769b-11eb-8149-e5adbf01bfae.png)
![image](https://user-images.githubusercontent.com/74927546/109040252-b5616700-769b-11eb-9ff3-7901dc27262b.png)
![image](https://user-images.githubusercontent.com/74927546/109040339-c9a56400-769b-11eb-8b19-dc17f94ee596.png)

**Additional context**

**Comment by Yoyoma22** [comment]
Because of access, I cannot create a branch to create a pull request.  Therefore i zipped up the code change and the diff and sent it to the developer via e-mail.

**Comment by TheElementalOfDestruction** [comment]
@Yoyoma22 Anyone can create a pull request on this repository. A branch in the repository is not necessary to do so; instead simply point the branch you are using to be a pull request to this repository instead of your fork.

**Comment by TheElementalOfDestruction** [comment]
prepareFilename was simply meant to adjust filenames (expecially subject that were being converted into file names) so that they did not contain any invalid characters. It was never meant for paths. After looking at the code, I see it was accidentally given a full path to use.

**Comment by praveenbehara** [comment]
Yes.. after a little bit of understanding of the code.. I see that the order itself is the wrong thing.. How to fix it here?

**Comment by TheElementalOfDestruction** [comment]
It'll be fixed in the next update. Should be within the next few hours.

**Comment by TheElementalOfDestruction** [comment]
The code is now in the right order. Again, until 0.29.0 this will not be *officially* supported, even if it technically works.

**Comment by Ginabot73** [comment]
Chad

**Comment by TheElementalOfDestruction** [comment]
This should now be working correctly in version 0.29.0

**Comment by TheElementalOfDestruction** [comment]
While I'm closing this issue, it should be noted that now that I am working on 0.30.0 which removes Python 2 support, I also plan to convert a lot of things to try and use pathlib to hopefully better deal with all the path nonsense that the module uses. After confirming (I think it was with you) that the usage of pathlib seemed to add a negligible difference in speed when disk read/writes were occurring soon after, I'm just going to eat the difference in favor of smaller, more reliable code.
