### ISSUE TITLE
extract_msg.exceptions.UnrecognizedMSGTypeError: file with msgtype IPM.NOTE can't be opened

### ISSUE THREAD

**Issue by NicholasKiefer** [TeamMsgExtractor/msg-extractor#201]
Sorry to reopen this issue, but when opening a msg file the function extract_msg.openMsg(path/to/file) fails with
```
extract_msg.exceptions.UnrecognizedMSGTypeError: Could not recognize msg class type "IPM.NOTE". It is recommended you report this to the developers.
```
I see that in utils.py it gets checked:
```
    elif classtype.startswith('IPM.Note') or classtype.startswith('REPORT'):
        msg.close()
```
but when opening with ```strict=True``` I can see that ```classtype=IPM.NOTE```. This mismatch in upper/lowercase unnecessarily raises that error, and prevents the module from opening that file. Can that check get extended to include 'IPM.NOTE' and not just 'IPM.Note'?

**Comment by TheElementalOfDestruction** [comment]
Based on the documentation from microsoft it looked like it should always have that exact case. What generated the msg file you are using?

I'll put a fix for this in the next update, but this really should not have been a problem based on my information.

**Comment by TheElementalOfDestruction** [comment]
Also, would it be possible for you to send me the file? I'd like to see if it might break anything else. If not I can refer you to a pre-release for the next version and you can test against that and let me know the results.

**Comment by NicholasKiefer** [comment]
The file was sent to me, so I don't know how it was generated. I'm very sorry to say that I can't share the file with you, there is confidential information in there that I cannot share, and removing everything seems to also not generate the error.
I can test it against a new version though.

**Comment by TheElementalOfDestruction** [comment]
This is the location of the current progress report for the next version of msg-extractor: https://github.com/TheElementalOfDestruction/msg-extractor

Please try to load it using this version (you can just download it and run an interpreter from that folder before import extract_msg) and see if using it gives you any errors. I have not been able to produce any major errors with this version (aside from it being unable to do HTML and RTF bodies at this time). As such I can only assume any errors your file may generate are likely to be rare edge cases, most likely due to a bad generator. I will, however, do what I can to account for them. 

Thank you.

**Comment by NicholasKiefer** [comment]
this version works! Thank you!
line 95 in message_base.py needs to read
```
if len(foundRecipients) > 0:
```
otherwise it will throw an error.

**Comment by TheElementalOfDestruction** [comment]
Oops. My test files (I made that change recently and so only tested a few on that part) never actually made it to that line. Thanks for pointing it out. Was renaming the variables to make them descriptive.

**Comment by TheElementalOfDestruction** [comment]
Lol, just found out that I was actually wrong and that the equality comparison's should always be case insensitive. I think when I first read that I saw "case-sensitive" instead, so whoops.

![image](https://user-images.githubusercontent.com/24580325/130371677-b87ae3b5-c2a6-442a-a888-85ed7b0319d3.png)

**Comment by TheElementalOfDestruction** [comment]
This should now be fixed in the new version based on my tests. Let me know if you have any issues.
