### ISSUE TITLE
Feature Request: Add support for Task objects

### ISSUE THREAD

**Issue by micheben** [TeamMsgExtractor/msg-extractor#212]
**Bug Metadata**
* Version of extract_msg: 0.28.7
* Your python version: Python 3.7
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
Files with a Outlook Task attachment fail with an extract_msg.exceptions.UnrecognizedMSGTypeError

**What code did you use or can we use to reproduce this error?**

```
from extract_msg import Message
b = open("ipmtask.msg","rb").read()
msg = Message(path=b)
```

**Is there a message.msg file you want to share to help us reproduce this?**
[ipmtask.msg.zip](https://github.com/TeamMsgExtractor/msg-extractor/files/7175286/ipmtask.msg.zip)

**Comment by TheElementalOfDestruction** [comment]
Changed from a bug report to Feature request (not a bug that it is not supported yet). Will get around to this at some point.

**Comment by TheElementalOfDestruction** [comment]
On a related note, you should try to avoid directly instantiating the Message class. Prefer using extract_msg.openMsg to ensure you get the correct class for your .msg file.

**Comment by micheben** [comment]
> Changed from a bug report to Feature request (not a bug that it is not supported yet). Will get around to this at some point.

Thought it might be forgotten, since it was instantiated as `BrokenAttachment` and not as `UnsupportedAttachment`. 

> On a related note, you should try to avoid directly instantiating the Message class. Prefer using extract_msg.openMsg to ensure you get the correct class for your .msg file.

Thanks for the note.

**Comment by TheElementalOfDestruction** [comment]
So "BrokenAttachment" is just a substitute for an attachment that had an error in loading while UnsupportedAttachment refers to an attachment type that just can't be supported at all (it's a very specific type that we check for). It was specifically the `UnrecognizedMSGType` error that should have given it away, however it's also not as clear as it could be. I'll add some changes to openMsg (which Attachment uses internally) that should make it more noticeable that we know the msg type exists but is just not supported. Will probably add another attachment type to also make it clear that it was specifically an unsupported msg type.

In the future I'll actually get around to adding it, just need to finish the next major version, then move to a version that will drop support for Python 2 so we can add more features. Will probably be added after that one.

**Comment by TheElementalOfDestruction** [comment]
By the way, any additional examples you can produce would help to make sure that we get everything you may want to access when you get an instance of the Task class (which is what you would get when that format is opened by the module). Also, any examples on how you would expect it to get saved would also be beneficial, with images or possibly actual files being the best.

**Comment by TheElementalOfDestruction** [comment]
Support for viewing many of the important task properties and opening task objects has been finished. Support for saving them will come later

**Comment by TheElementalOfDestruction** [comment]
Completed in 0.35.0. Let me know if you have any issues with it.
