### ISSUE TITLE
UnrecognizedMSGTypeError in openMsg Causes Attachments to be BrokenAttachment instead of UnsupportedAttachment.

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [TeamMsgExtractor/msg-extractor#214]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Version of extract_msg: [0.28.7]

**Describe the bug**
In the call to `openMsg` from `Attachment`, if the `UnrecognizedMSGTypeError` is thrown, and the attachment behavior is not to simple log the error, then the attachment with be a `BrokenAttachment` instead of `UnsupportedAttachment`.

**Comment by Ginabot73** [comment]
****
