### ISSUE TITLE
Typo in command-line argument parsing

### ISSUE THREAD

**Issue by toBeOfUse** [TeamMsgExtractor/msg-extractor#226]
Hello this is a very small issue. On this line:
https://github.com/TeamMsgExtractor/msg-extractor/blob/125ad0252b1eccc70a11dbcda7ef94208215d1f1/extract_msg/utils.py#L221
There is a typo where "fallback" is spelled as "fallbac". This breaks command line argument parsing. Thank you

**Comment by toBeOfUse** [comment]
Also. On this line
https://github.com/TeamMsgExtractor/msg-extractor/blob/125ad0252b1eccc70a11dbcda7ef94208215d1f1/extract_msg/message.py#L178
This condition will never be true because `zip` is a builtin and is always a truthy thing. I think it is supposed to be `_zip`

**Comment by TheElementalOfDestruction** [comment]
For the second one it looks like you are looking at the master branch, which does not reflect the most current version of the module. Once 0.29.0 was released, further updates on that version (0.29.*) were moved to it's own branch. Exactly the second part was detected and *fixed* in newer versions, and a fix exists as well in 0.30.0 in next-release (the newest unfinished version).

The first, however, was not detected and will be fixed quickly.

**Comment by toBeOfUse** [comment]
That makes sense; the first problem is what I ran into after installing with PIP and then I downloaded the master branch to fix it locally and make it work and ran into the second problem. Thank you

**Comment by TheElementalOfDestruction** [comment]
Yeah, the change in how the branches work literally happened a few days ago, so I don't blame you for not knowing. I'm more surprised I didn't see that confusion coming, lol. I'll get 0.29.3 out in a few minutes with a fix and run a quick test to double check that there shouldn't be anything else. 

Of course I forgot to actually run the program from the command line for testing, lol.

**Comment by TheElementalOfDestruction** [comment]
Oh dear, yeah looks like I forgot to go and change main to reflect some of the changes to the save function. Whoops.

**Comment by TheElementalOfDestruction** [comment]
Alright, you kind of opened up a can of worms with this issue, showing me there were several major issues in __main__. This should all now be fixed. Let me know if you have any more issues.
