### ISSUE TITLE
zip or _zip?

### ISSUE THREAD

**Issue by bdelacey** [TeamMsgExtractor/msg-extractor#227]
I had some problems saving files. There are four places in message.py which refer to zip, and other places refer to _zip.

I changed zip to _zip for my test runs and I was able to save my messages after that.

I was running this on Ubuntu, in a Visual Studio Code gui - running with Python3.

Great software - thank you for sharing it.

**Comment by TheElementalOfDestruction** [comment]
What version are you using? If it is not 0.29.3 then you have the wrong version.

**Comment by bdelacey** [comment]
It appears I was using  Latest commit ce8e28e 7 days ago

**Comment by TheElementalOfDestruction** [comment]
That is the master branch, which is not receiving updates to 0.29.*. After 0.29.0 I immediately broke it into two branches so that bugfixing patches would be separate from main releases. This allowed me to have a version that would still support Python 2 but I wouldn't have to provide feature updates for it. 

It is highly recommended that you install the package from pypi, as all updates to the master branch are matched there anyways.

**Comment by bdelacey** [comment]
Thanks ... I see now I was on master ... I did think I installed initially from pypi and was hitting the bug, after which I downloaded the source, made the changes mentioned and things worked ... Is it possible pypi somehow installed Master initially? I'll reinstall and restart - appreciate the explanation. And it was good to walk through some of the code more after hitting that blocking bug! (If there are any examples of how KWARGS are used in various combinations on SAVE, that would be a big help!!!)

**Comment by TheElementalOfDestruction** [comment]
In installing it, if at any point you installed from master instead that could have done it. It's also possible a package you installed referred to it through github which is... interesting.

As for the kwargs, read the documentation of the save functions and they list each of the kwargs. They are grouped together by relevance to each other in it (so in the section talking about format, it talks about json, html, rtf, etc). I''m not great at documentation and am hoping to find someone to help rewrite a lot of the docs, finish writing the readme, and help create a wiki, lol.

**Comment by bdelacey** [comment]
I’ll do a write up on kwargs and share it. Ty

**Comment by TheElementalOfDestruction** [comment]
Just for clarification, `**kwargs` is collecting all the *many* possible keyword arguments that can be provided, otherwise it would be a nightmare to look out. Previously I had all the arguments but it got to be way too much, lol.

**Comment by TheElementalOfDestruction** [comment]
Here is a list of available keywords that the save will take (along with a very brief description of them). Hoping it will help you out:
* `html`: Enables html saving.
* `rtf`: Enables rtf saving.
* `raw`: Enables raw saving.
* `json`: Enables json saving.
* `customPath`: Sets the path to create the output folder in.
* `customFilename`: Sets the name to use for the created output folder.
* `useMsgFilename`: Determines whether to use the same name as the file that created the Message instance (not available for files created with a data stream unless `Message.filename` has been set.
* `maxNameLength`: Used to control the length of filenames to help with deeply embedded msg files that would cause errors on windows.
* `zip`: The name of a zipfile to write the output into or an instance to use to place the output into.
* `allowFallback`: Allows the save function to revert to another format for saving if the selected one is not available.
* `saveHeader`: Tells the save function to create a file with the raw or generated header separate from the body.

Options forwarded to attachments:
* `zip`: See above.
* `maxNameLength`: See above.
* `contentId`: Specifies that the attachments should be saved using their Content IDs as the name.

To be added in 0.30.1:
* `preparedHtml`: Uses the HTML body that has been prepared with attachments when used in conjunction with the `html` option.

To be added in the future:
* `maxPathLength`: parameter that will be used in advanced path calculations to better determine how to name the output to not overflow a path length limit.
