### ISSUE TITLE
msg.py is missing 'import pathlib'

### ISSUE THREAD

**Issue by TterraggarretT** [TeamMsgExtractor/msg-extractor#239]
Simple fix issue, getting a 'pathlib is not defined' error. I was able to fix locally by just adding 'import pathlib' to the msg.py script.

**Comment by TheElementalOfDestruction** [comment]
Apparently I never actually tested giving it a pathlib path. I'll add this fix to the next release I am making.

**Comment by TheElementalOfDestruction** [comment]
I'm posting version 0.30.7 right now, which has the fix (plus some bonus stuff).

**Comment by TheElementalOfDestruction** [comment]
This is fixed in version 0.30.7. Let me know if you have any other problems

**Comment by TterraggarretT** [comment]
Yep, just reinstalled and it works, thanks
