### ISSUE TITLE
Docstring and param name mismatch for attachment.save

### ISSUE THREAD

**Issue by scotscotmcc** [TeamMsgExtractor/msg-extractor#253]
**Bug Metadata**
Version of extract_msg: 0.30.11
Python 3.9.7

In the docstring for `attachment.save()`, it says "...The first thing that is checked is if you have provided :param CustomFileName:...". However, the actual parameter checked in attachment.getFilename() is `customFilename`, with a lower-case n.

Using "CustomFileName" in the param in `.save()`, with the capital N, results in it not being checked/used.

Probably should just be a fix to the docstring to match what is in `attachment.getFilename()`, but I guess you could also do something wild like use all lower for the actual check and force to lower whatever is sent in, or something.

**Comment by TheElementalOfDestruction** [comment]
Just a complete typo, not even sure how I managed to do it. Thanks for pointing it out.

**Comment by TheElementalOfDestruction** [comment]
Alright, I fixed the typo as well as issues in a few of the other docstrings. Let me know if you find any more.
