### ISSUE TITLE
How to save attachment to a particular directory, I am trying to use the Attachment class but I am getting error

### ISSUE THREAD

**Issue by Laxmi530** [TeamMsgExtractor/msg-extractor#257]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Version of extract_msg: [0.30.12]
* Your python version: Python [3.8]
* How did you launch extract_msg?
  - [x] I used the extract_msg package

**Describe the bug**
I am trying to save some attachment from a msg file to a particular directory and when I am using the Attachment class I am getting error. I tried some other method but the attachments are getting saved in the working directory. So can anyone help me how to save the attachment to a particular directory. I noticed one thing the doc string are not well explained and there is no example.
[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
att_msg = extract_msg.Attachment('unicode.msg')
att_msg
```

Is there a message.msg file you want to share to help us reproduce this?
- https://github.com/TeamMsgExtractor/msg-extractor/tree/master/example-msg-files
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
TypeError                                 Traceback (most recent call last)
<ipython-input-16-f02ae309b6db> in <module>
----> 1 att_msg = extract_msg.Attachment('unicode.msg')
      2 att_msg

TypeError: __init__() missing 1 required positional argument: 'dir_'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/76505459/170446542-117e87bf-e14c-48fd-88b8-410780a74ff2.png)

**Additional context**
cant understand what will be the path neither find any example nor the doc string explained well.

**Comment by TheElementalOfDestruction** [comment]
Attachments are not meant to generally be initialized manually, which is why it's not mentioned like this. You open the msg file with extract_msg.openMsg and then access the attachments from that (just do .attachments on the object you get back and you have a list of attachment objects).

**Comment by TheElementalOfDestruction** [comment]
Sorry, I also skimmed the issue a bit and missed some things. The python interpreter's `help` method is the best for learning how to use things in the module while the official documentation is still being developed. Time constraints have made this a slow process. `Attachment.save()` takes several possible keyword arguments described in the docstrings, however I noticed one that doesn't appear to be mentioned is `customPath`. It is mentioned in `Message.save()`, fortunately, but appears to have been overlooked. Simply pass `customPath = 'path/to/save'` as an argument and it will save to that directory (assuming it exists)

**Comment by TheElementalOfDestruction** [comment]
I'm currently fixing the documentation to reflect the missing information I specified in my last message. Again, as the timing means you likely missed it, use `customPath` as an argument when saving the attachments to change the save directory

**Comment by Laxmi530** [comment]
Thanks for the updating. Now I came up with two new question.
1. Still can't understand the parameter in Attachment class 'dir_: the directory inside the msg file where the attachment is located'. If you can provide any example that will be better. I am very excited to use this class.
2. Suppose I have a msg file that msg file have some pdf attachment and some jpeg attachment and I want to save the jpeg attachment not the pdf attachment. Can you please guide me how to do this ?

**Comment by TheElementalOfDestruction** [comment]
1. An msg file is an archive (think like a zip folder) and an attachment is done inside of it using a folder starting with `attach_version' or something (I'd have to check for the exact start). The message class will automatically find all of these folders and use them to generate an attachment. Try opening an msg file with 7zip or other archive program that supports .msg files to see this visually.
2. Message.attachments gives a list of the attachments for a message. If you want to save a specific one of those, use the same method of that specific attachment. Example code:
```py
import extract_msg

msg = extract_msg.openMsg('path/to/msg/file.msg')

# If the msg file has at least 1 attachment, save only the first one.
if len(msg.attachments) > 0:
    # Save the first attachment to the current directory. You can use `customPath` as an argument to change the save directory.
    msg.attachments[0].save()
```

**Comment by Laxmi530** [comment]
Thanks for the code. 
In the code your are saving the first attachment which is in 0th index and we dont know the attachment is a pdf or jpeg. But my concern is you open the msg file and and inside the msg file there are some number of attachments if the attachment is a jpeg or png i want to save that not other attachments. So please guide me how to do ?

**Comment by TheElementalOfDestruction** [comment]
Check the attachment. It is common for the attachment names to have a correct extension so look for it to end with .jpg or .png. If that isn't working, checking the first few bytes of the `data` property will (assuming the type is not msg). There is also a property I'm adding soon to grab the mimetype which could also be checked, assuming it exists.

**Comment by Laxmi530** [comment]
![image](https://user-images.githubusercontent.com/76505459/170815010-61b2c82a-3bc3-4fcd-8875-e67adb187f95.png)
Thanks for the replay.
I tried this code but this is not working. Can you please guide me how to get the attachment file name?

**Comment by TheElementalOfDestruction** [comment]
The save function has no way to filter attachments (right now the necessary code would be too complex and unreliable) but you can manually go through the attachments array and use `Attachment.shortFileName` or `Attachment.longFileName` (attachments may have one, the other, or both) then check if that string ends with .jpg or .png. Additionally, you could also try the getFilename function which does what it can to get a filename depending on the arguments. Default arguments (don't give it anything) are your best bet.

```py
for attachment in msg.attachments:
    # This is a dirty way to do it, but this will do what it can to get the file name.
    filename = attachment.getFilename()
    if filename.endswith('.png') or filename.endswith('.jpg')
        attachment.save(customPath = 'directory/to/save/to`)
```

**Comment by Laxmi530** [comment]
Now its working perfectly. Thanks a lot for your help my main issue got resolved. Can you please help me how to get the simple text from the body as it is in the mail rather then getting bunch \r and \n along with the text.  
![image](https://user-images.githubusercontent.com/76505459/170834640-a12543c5-1e5e-4910-949e-e798ae27ec70.png)

**Comment by TheElementalOfDestruction** [comment]
The \r and \n is part of the body, you just don't normally see it like that. The reason it's showing like that is because you aren't printing it, you are showing the representation of it (which shows special characters in that format). `print(data.msg.body)` will show how you are expecting it

**Comment by Laxmi530** [comment]
Thanks for the replay,
But I am unable to extract the table as it is in the mail it is extracting only the character and not in the same order as it is in the mail. Can you please help with this how can I do ?

**Comment by TheElementalOfDestruction** [comment]
I'm sorry, I don't understand the question as it has been written.

**Comment by Laxmi530** [comment]
You understand it correctly 
(Message.htmlBody) it is returning the html detail but how to get the table. Shall I need to use any other library for extracting the table from html or your library is providing that.

**Comment by TheElementalOfDestruction** [comment]
We cannot possibly support every single feature for HTML when that is not the design of this library. As such, once you have retrieved the HTML, you will have to use a different one for analyzing it. I recommend bs4 (beautifulsoup4) as it is what the library itself uses for the manipulation it sometimes needs to do on the HTML. You can find guides on how to use it pretty easily.

**Comment by Laxmi530** [comment]
Thanks for help.
Now I cam with another issue, I have attached the screen shot. This is the one 
![image](https://user-images.githubusercontent.com/76505459/172142500-d3f56b42-8992-4069-b228-5f3270506b9f.png)

This is the second method I tried.
![image](https://user-images.githubusercontent.com/76505459/172142796-3ccd0ef0-5827-4503-847f-f4a867dfba54.png)

This is the third method I tried 
![image](https://user-images.githubusercontent.com/76505459/172143452-4d4f006d-db3b-4ab3-aa0c-6969d1be5d7e.png)

Can you please help when I pass a path to the customPath make sure

**Comment by TheElementalOfDestruction** [comment]
The first method is correct. Unfortunately the python errors aren't always helpful. Have you made sure the folder you are specifying already exists? If not, create it then run the code again. The functions will not create folders to match the custom path to reduce the number of os calls it would need.

The reason the second method didn't work is it looks like the folder actually doesn't exist, and the os call you used has no return (so it returns an empty value). This empty value is then given to customPath instead of the path you made, causing it to have a problem I hadn't considered. I'll need to add some type validation to it before it's manipulated to give a clear indicator of what the problem is.

So what you do is on you do the os.makedir first *then* give the function the same path you gave it. That will work

**Comment by Laxmi530** [comment]
So what you do is on you do the os.makedir first then give the function the same path you gave it. That will work - This is also not working, while os.makedir creating the directory.

![image](https://user-images.githubusercontent.com/76505459/172146847-0c40d59e-fde1-494f-b910-b0fb659d9188.png)

**Comment by TheElementalOfDestruction** [comment]
is.makedir has no return, so in your code `path_dir` is the value `None`.

Instead, put the path you give into a variable, then give that variable to both.

```py
path_dir = r'D:\Email_attachment`
os.makedir(path_dir)
msg_data.saveAttachments(customPath = path_dir)

**Comment by Laxmi530** [comment]
But there is an another issue in .save() method because in .save() method it is creating another directory inside the path directory. Actually I am trying the .save() method using you above mentioned method in another system there it is not working. I follow your above method it is working for saveAttachments() but not for .save(). Can you give some hint how to tackle the error.

**Comment by TheElementalOfDestruction** [comment]
Save will take the custom path and apply it to the message itself. The message creates a folder for itself typically based off of the subject. You can change the name of this folder as well (use the customFilename parameter). Attachments are then saved into that folder along side the body, to keep everything grouped together. If you would like to save the body to a different location than attachments, you'll currently have to manually use saveAttachments and then access the body and save it to a file yourself.

**Comment by Laxmi530** [comment]
Can you give some idea, suppose I have a msg file inside that in attachment there is another msg file inside that in attachment there is another msg file inside that msg file there is an attachment I have to save that. Already you explained that how to save the  attachment but how can we go msg file inside msg inside msg inside attachment

**Comment by TheElementalOfDestruction** [comment]
Attachments have a property `Attachment.type` which will be the string `"msg"` (right now anyways, although this will likely be changed to an enum that makes things more organized) if it is a message itself. This message can be accessed from `attachment.data`, and is already an instance you can use.
```py
for att in msg.attachments:
    # This code is not currently compatible with signed attachments, which are only on very specific messages, so we just filter them out from the check for now.
    it isinstance(att, extract_msg.Attachment):
        # This commented line approximates how you might check in the future, but the line after is what you currently use.
        #if att.type == extract_msg.enums.AttachmentType.MSG:
        if att.type == 'msg':
            newMsg = att.data
            # At this point, newMsg has the message in it, and you can access it's body, attachments, etc. in the same way as the original message. Add code here to do whatever you want.
```
One problem with this approach is that it won't give you direct access to further embedded msg files as it doesn't have another for loop. To counteract this, a section of code like this will give you a list of every message instance in the created tree:
```py
found = [msg]
# We start off with just the top msg file and the program will work down from it. You could also put whatever messages you want into it and it can do more than one at once.
toProcess = [msg]

while len(toProcess) > 0:
    currentMessage = toProcess.pop()
    for att in currentMessage.attachments:
        if isinstance(att, extract_msg.Attachment)
            if att.type == 'msg':
                found.append(att.data)
                toProcess.append(att.data)
```
After the while loop, the list `found` contains all of the messages and embedded messages.

**Comment by Laxmi530** [comment]
In your above code in toProcess = [msg] and found = [msg] what will be the msg.

![image](https://user-images.githubusercontent.com/76505459/172344606-f5959c10-3e99-4fc5-a848-43b6533ffe5b.png)

**Comment by TheElementalOfDestruction** [comment]
Yes, replace `msg` with whatever variable you are using. If you want to include the original message in the results, include it inside the square brackets for found, otherwise leave them empty.

**Comment by Laxmi530** [comment]
Here it becomes an infinite loop. Can we have a call so I can explain you the whole details.

![image](https://user-images.githubusercontent.com/76505459/172347643-c3aa0fa9-3856-4186-a65f-a40befa6c0d1.png)

**Comment by TheElementalOfDestruction** [comment]
You modified one of the lines and introduced an error because it will always find a new valid attachment each loop. The line *must* be `for att in currentMessage.attachments:`. Do not change this line. The variable name must match up exactly with the line before to ensure it's always looking only at attachments it has not already processed

**Comment by Laxmi530** [comment]
This is what I am getting when reading an .rpmsg file or an protected outlook .msg file.  

![image](https://user-images.githubusercontent.com/76505459/173302223-5382ce6d-0a87-4ceb-97b2-1819b4e4bc9d.png)


![image](https://user-images.githubusercontent.com/76505459/173302626-32489679-df98-4b47-aeab-fd4145f5c77c.png)

**Comment by TheElementalOfDestruction** [comment]
If you are using the version of unwrap that doesn't include the original message in the output (I'd need to check the code to confirm) then it will only go through the bodies for embedded msgs, giving you an empty list. It looks like no error occurred while opening it, so it probably just had no embedded msg files in it. 

If the line in unwrap_attachments says `msgFiles = []` then it will not return the original in that list. Change it to `msgFiles = [msg]` (assuming you kept the parameter name the same) to make it also include the original file in the list.

**Comment by Laxmi530** [comment]
This is the code which you shared for unwrap_attachments.
![image](https://user-images.githubusercontent.com/76505459/173304190-42859cea-3e82-4ba7-8bf2-7273a43fe2c9.png)

**Comment by TheElementalOfDestruction** [comment]
Yeah, I can confirm it doesn't include it. Just change the line how I said and you should get a proper result

**Comment by Laxmi530** [comment]
Post changing the code this is the output

![image](https://user-images.githubusercontent.com/76505459/173305405-44c498ed-d993-47c1-bc2f-ccfb00e15edb.png)


This is the code I changed.

![image](https://user-images.githubusercontent.com/76505459/173305991-f8ced7fe-de47-4231-924a-95ba63049150.png)

**Comment by TheElementalOfDestruction** [comment]
None is the type returned when something you tried to access doesn't exist. Looks like that file just literally doesn't have a plain text body then. It might have an RTF body (`msg.rtfBody` instead of `msg.body` to check) or even an HTML body (`msg.htmlBody` instead of `msg.body` to check), or it may have no available body due to the type of file it is. I'd have to look into the exact format it is using to try and figure out if that type of message has an accessible body if none of those work.

**Comment by Laxmi530** [comment]
Post trying remaining two method.

![image](https://user-images.githubusercontent.com/76505459/173308229-2015205f-e911-4bb1-a2a0-169d1284048d.png)

**Comment by TheElementalOfDestruction** [comment]
Yep, the file you are using has no body that the module can understand. Only thing left is to tell me what `msg_data.classType` gives you so I can figure out where the documentation is.

**Comment by Laxmi530** [comment]
This is the out put msg_data.classType. I don't have permission to share that msg file or I would have been share with you for better clarification. 

![image](https://user-images.githubusercontent.com/76505459/173493834-f47c339c-85cd-42b5-b1f0-570c33abd7d9.png)

**Comment by TheElementalOfDestruction** [comment]
That's the type of a regular message, so it might just be some special property in the file that actually marks it. What it is, I don't know and don't know what to look for. I'm afraid that without an example file to run tests on I won't be able to help.

**Comment by Laxmi530** [comment]
Yes I can understand  without an example file you cant reach to any point and I cant share those msg files.
As of now I am able to do most of the operations. If I am facing any issue or if I find any bug I will inform you.
