### ISSUE TITLE
HTML conversion issue

### ISSUE THREAD

**Issue by stat422** [TeamMsgExtractor/msg-extractor#271]
Recently started getting issues with MSG files failing to convert to HTML 

```
Error with file "test.msg": Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lark/lexer.py", line 486, in lex
    token = self.root_lexer.next_token(lexer_state, parser_state)
  File "/usr/lib/python3.6/site-packages/lark/lexer.py", line 400, in next_token
    state=parser_state, terminals_by_name=self.terminals_by_name)
lark.exceptions.UnexpectedCharacters: No terminal matches '\' in the current parser context, at line 10 col 16

\intbl\plain\f0\~{\*\htmltag0 </Span>}{\*\htmltag0 </P>
               ^
Expected one of:
        * CONTROLWORD
        * RTFESCAPE
        * CONTROLSYMBOL
        * CLOSEPAREN
        * TEXT
        * OPENPAREN

Previous tokens: Token('CONTROLWORD', '\\f0')
```

**Comment by TheElementalOfDestruction** [comment]
Closing as not an issue with extract-msg. See https://github.com/TeamMsgExtractor/msg-extractor/issues/249 and the issue on RTFDE https://github.com/seamustuohy/RTFDE/issues/5

Simply put, there are some issues with RTFDE which we use to get the HTML from the RTF body should there be no HTML stream. We also have a way to generate it (sort of) through the plain text body, but it is rather basic and just wraps it in HTML tags.

Starting in version 0.34.0 an option for opening msg files was adding called `ignoreRtfDeErrors`. You can provide `ignoreRtfDeErrors` to `openMsg` to ignore these issues and fall back to a more primitive method for generating the HTML body. Additionally, if you have a function youd like to use that takes the RTF body and the type of body you want to get out of it, you can provide that function with the `deencapsulationFunc` argument to `openMsg`. 

```
:param deencapsulationFunc: Optional, if specified must be a callable
    that will override the way that HTML/text is deencapsulated from the
    RTF body. This function must take exactly 2 arguments, the first
    being the RTF body from the message and the second being an instance
    of the enum DeencapType that will tell the function what type of
    body is desired. The function should return a string for plain text
    and bytes for HTML. If any problems occur, the function *must*
    either return None or raise one of the appropriate functions from
    extract_msg.exceptions. All other functions must be handled
    internally or they will continue. The original deencapsulation
    method will not run if this is set.
```

**Comment by TheElementalOfDestruction** [comment]
Additionally, from the command line you can use `--ignore-rtfde` for the same effect
