### ISSUE TITLE
TypeError: unsupported format string passed to bytes.__format__

### ISSUE THREAD

**Issue by jeremrav** [TeamMsgExtractor/msg-extractor#272]
**Bug Metadata**
* Version of extract_msg: [0.34.3]
* Your python version: Python [3.9.12]
* How did you launch extract_msg ?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
Hello, I create a software that reads ".msg" files to read and find some informations inside. When I run my script with VsCode I have no problem. But when I build the script in exe and I run it, I got this error below. I don't know if the problem is with my build exe (maybe bad importation but I couldn't find it) or something else.
I used pyinstaller to build exe.
Any idea on how to resolve this? Thanks!

**My code**
```
class Mail:

    def __init__(self, mail_path:str):
        """ Create mail object.
        """

        self.path = mail_path
        self.favorite = "0"

        if os.path.exists(self.path):
            self.email = extract_msg.Message(self.path)
```

**Traceback**
```
Traceback (most recent call last):
  File "extract_msg\message_base.py", line 339, in header
    return self._header
AttributeError: 'Message' object has no attribute '_header'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract_msg\message_base.py", line 250, in date
    return self._date
AttributeError: 'Message' object has no attribute '_date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract_msg\properties.py", line 129, in date
    return self.__date
AttributeError: 'Properties' object has no attribute '_Properties__date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threadclassmails.py", line 61, in run
  File "mail.py", line 25, in __init__
  File "extract_msg\message.py", line 28, in __init__
    super().__init__(path, **kwargs)
  File "extract_msg\message_base.py", line 78, in __init__
    self.header
  File "extract_msg\message_base.py", line 348, in header
    header.add_header('Date', self.date)
  File "extract_msg\message_base.py", line 252, in date
    self._date = self._prop.date
  File "extract_msg\properties.py", line 132, in date
    self.__date = self.get('00390040').value.__format__('%a, %d %b %Y %H:%M:%S %z')
TypeError: unsupported format string passed to bytes.__format__
```

**Build code**

import PyInstaller.__main__
```
PyInstaller.__main__.run([
    '--clean',
    'main.py',
    '--windowed',
    '--onedir',
    '--console',
    '--icon=./src/img/logosei-groupe_moyen.ico',
    '--name=RechercheMails'
])
```

**Comment by TheElementalOfDestruction** [comment]
Was about to say I believe this was an issue with the packing of tzlocal, but actually I think the problem is that there is no check for if that date is a bytes type (because it's too far in the future or possibly too early). When the date fails to parse it just remains stored as raw bytes. It's either that happening or something to do with tzlocal.

If you enable logging (setup a logger somewhere that actually logs to the console or a file) and give me the reported timezone for the date I can check it out, but I'll make sure the current code for the next version has a patch for just ignoring it if it ends up being bytes there.

**Comment by jeremrav** [comment]
[app.log](https://github.com/TeamMsgExtractor/msg-extractor/files/9008918/app.log)
Thank you for the very quick reply!
I have attached the log to the comment.

**Comment by TheElementalOfDestruction** [comment]
Nope, looks like an issue with packaging tzlocal. It's saying it can't recognize the timezone in the message that shows the original exception. So I believe this is because that information is stored in a resource file that's not properly being packaged.

**Comment by jeremrav** [comment]
do you know what the wrongly packaged resource is? I'm sorry to ask you, I only started programming in python 3 years ago... ^^ or maybe where can I find this information? Anyway thank you for your reply !

**Comment by TheElementalOfDestruction** [comment]
I don't know what it is, but you could try their repository or try checking the module you have installed for any resource files it has. However it looks like you should be able to provide an option to the PyInstaller thing to tell it to grad a packaged resource files, so long as they are in it's folder. Keep in mind you may also get some minor issues with extract_msg if it's resource files are not included either, as it has log configuration files for setting up the command line logging or just regular logging.

**Comment by jeremrav** [comment]
Thanks ! I found, I have to import all the "tzdata" resource with pyinstaller. 
`
import PyInstaller.__main__

PyInstaller.__main__.run([
    '--clean',
    'main.py',
    '--windowed',
    '--onedir',
    '--collect-all=tzdata',
    '--icon=./src/img/logosei-groupe_moyen.ico',
    '--name=RechercheMails'
])
`

**Comment by TheElementalOfDestruction** [comment]
Version 0.35.0 has fixed the related in code issues. It should now better report an issue with using tzlocal that is not caused by an invalid date but rather the time zone failing to be acquired.
