### ISSUE TITLE
I/O operation on closed file for extracting special type of attachment

### ISSUE THREAD

**Issue by pratiknht** [TeamMsgExtractor/msg-extractor#273]
**Bug Metadata**
* Version of extract_msg: 0.34.3
* Your python version: Python 3.8.10
* How did you launch extract_msg?
  - [ ] I used the extract_msg package

**Describe the bug**
If the email (msg file) has a special attachment of Outlook email then facing following error:
Hence not able to extract the attachment from the email.
- **method**: msg.attachments

- **error**: : ValueError : I/O operation on closed file.

- Unfortunately, I cannot share the msg file due to its confidential contents

**Additional context**
Gives an error if the email (msg file) has a special attachment of Outlook email generated from the desktop app.
Below methods works fine for the same msg file:

1. msg = extract_msg.Message(msg_file)
2. msg.sender
3. msg.date
4. msg.subject
5. msg.cc
6. msg.body.rstrip()
7. msg.to

Gave error only for **msg.attachments**

**Comment by TheElementalOfDestruction** [comment]
Can you give the exact code you were using that gave an issue as well an an exact traceback? The given data is effectively meaningless.

From the error message, the only thing I can guess is that the msg file was closed at some point before it was done being used, but without a traceback and code it's effectively impossible to understand why.

**Comment by pratiknht** [comment]
Let me see if I can send you a sample email file with the same issue along with the code.

**Comment by TheElementalOfDestruction** [comment]
I can't see anything in the module that would allow it to close early like that except for using it incorrectly. For example, this code *might* cause a similar issue:
```python
with extract_msg.openMsg('path/to/msg.msg') as msg:
    body = msg.body
# Notice this line is not indented.
attachments = msg.attachments
```
If the last line is loading attachments, it would be placing itself after the with block, which would call __exit__ and close the file before the next line. This is intentional Python behavior. 

Just the code used and a traceback it gives would be enough to get started looking for an issue, as it is more likely related to code than any particular file.

**Comment by TheElementalOfDestruction** [comment]
Normally the code I showed above actually wouldn't have given you an error until much later if you tried to access a specific property that wasn't already loaded, but a mistake in a newer version meant that attachments aren't being preloaded like they are supposed to be.

**Comment by pratiknht** [comment]
Hi, I  have rectified the issue, 
the special outlook attachments are saved as a folder (and not a nested msg file) that was not being processed in API In-Memory.
So saving the in-memory msg file on disk worked for me.

I appreciate your response @TheElementalOfDestruction.
This task can be closed.
Thanks.
