### ISSUE TITLE
msg.attachment.save() please add a feature to overwrite existing file

### ISSUE THREAD

**Issue by aspirinmatt** [TeamMsgExtractor/msg-extractor#288]
I'm using param customFilename: in save(). If a file with same customFilename already existed in path, this function will created a new file with rename to customFilename + '(2)' . Is that possible to add a param which I can choose to overwrite existing file without rename it? Thanks!!!

**Comment by TheElementalOfDestruction** [comment]
I'll consider adding something like that. Unfortunately zip files pose a problem as trying to overwrite a file in one just creates a second file with the exact same name. However, the reason it exists is because attachments can end up having the same name even when attached to the same MSG file, so the module does some renaming to make sure all of them are extracted.

This could also cause problems if a folder with the same name happens to exist in the directory, as a naming conflict could cause exceptions to be thrown when trying to write the attachment. It's a bit of a complicated mess.

**Comment by aspirinmatt** [comment]
@TheElementalOfDestruction 
Hello, I have another question regarding the attachment.save() function.

I have a msg file with attachments looks like this:
![image](https://user-images.githubusercontent.com/20898953/186648044-1efadfe6-679a-451a-9d00-8eeab5eff292.png)

Inside there are .msg file and also "Outlook Item" with no extension. Not sure what "Outlook Item" is, but when I open it in outlook it looks just like a .msg file. But seems save() function will save "Outlook Item" as a folder (the type is AttachmentType.MSG), and save .msg file as it is (the type is AttachmentType.DATA):
![image](https://user-images.githubusercontent.com/20898953/186649160-5450b099-1f9a-4500-a432-d8224197389a.png)

Is this expected behavior and can I save "Outlook Item" as .msg file? Thanks!

**Comment by TheElementalOfDestruction** [comment]
> @TheElementalOfDestruction Hello, I have another question regarding the attachment.save() function.
> 
> I have a msg file with attachments looks like this: ![image](https://user-images.githubusercontent.com/20898953/186648044-1efadfe6-679a-451a-9d00-8eeab5eff292.png)
> 
> Inside there are .msg file and also "Outlook Item" with no extension. Not sure what "Outlook Item" is, but when I open it in outlook it looks just like a .msg file. But seems save() function will save "Outlook Item" as a folder (the type is AttachmentType.MSG), and save .msg file as it is (the type is AttachmentType.DATA): ![image](https://user-images.githubusercontent.com/20898953/186649160-5450b099-1f9a-4500-a432-d8224197389a.png)
> 
> Is this expected behavior and can I save "Outlook Item" as .msg file? Thanks!

See https://github.com/TeamMsgExtractor/msg-extractor/wiki/Why-it-is-currently-impossible-to-save-an-embedded-MSG-file-as-a-MSG-file

**Comment by aspirinmatt** [comment]
Thank you, it's very clear

**Comment by TheElementalOfDestruction** [comment]
Alright, bit of news on this, this should now be handled when the new version (0.42.0) is released. I'm adding a new keyword argument `overwriteExisting` that will tell the attachment save functions to only check name collisions if we are not trying to overwrite anything. I may extend this to also attempt to do something similar with `MessageBase.save`, but I'm not currently sure that I want to do that. If I do decide to do that, it will be before the release.

I can't say exactly when the release will be, unfortunately, but do know that the feature is coming as I am trying to close a large number of existing issues while waiting for an update to a dependency to be released. However, you can preview the update by installing from the next-release branch. If you do, let me know if any issues arise.

Additionally, my response to see why embedded MSG files cannot be saved no longer applies, as a few updates back I took the time to go through the documentation and add a feature that could do that.
