### ISSUE TITLE
Making .txt Files from MSG without Folder

### ISSUE THREAD

**Issue by enesertu** [TeamMsgExtractor/msg-extractor#296]
Hi,

I save txt files from msg. But library creating folder and adding txt file to the folder.

Can i make the txt file without folder?

**Comment by TheElementalOfDestruction** [comment]
I mentioned in the other issue that the save function does not have a way to do this at this time. However, you can use native python functionality to save the result of `msg.getSaveBody()` to a file.

```py
with open('path/to/file.txt', 'wb') as f:
    f.write(msg.getSaveBody())
```

**Comment by enesertu** [comment]
Ok i didn't see that sorry. Thanks for your help
