### ISSUE TITLE
Request: how to only save msg attachments from msg without recursively extract them

### ISSUE THREAD

**Issue by WhistleMaster** [TeamMsgExtractor/msg-extractor#299]
Hi !

Thanks for the great tool ! I would like to extract from a bunch of msg emails their attachments, which are themselves msg files, but the extraction is also performed on the msg attachments recursively.

Is there a way to only save the msg attachments file without extracting them as well ?

Thanks !
Kind regards,

WM

**Comment by TheElementalOfDestruction** [comment]
Are you asking to save them as .msg files? If so, the wiki and several issues have explanations for why that is currently not possible to do. Otherwise, I don't actually understand what you are asking.

**Comment by WhistleMaster** [comment]
Indeed, I saw the wiki page afterward. I'm putting the link here for history: https://github.com/TeamMsgExtractor/msg-extractor/wiki/Why-it-is-currently-impossible-to-save-an-embedded-MSG-file-as-a-MSG-file
