### ISSUE TITLE
Error when saving attachment with a `customPath`

### ISSUE THREAD

**Issue by programmarchy** [TeamMsgExtractor/msg-extractor#322]
**Bug Metadata**
* Version of extract_msg: 0.38.4
* Your python version: Python 3.9.14
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
When using a `customPath` in `attachment.save` an `UnboundLocalError` exception may be thrown.

**What code did you use or can we use to reproduce this error?
```
msg = extract_msg.Message(file_path)
for attachment in msg.attachments:
  attachment.save(customPath=output_path)
```

**Traceback**
```
Traceback (most recent call last):
  File "/home/user/project/process_msg_emails.py", line 46, in <module>
    extract_msg_file(file_path, output_path)
  File "/home/user/project/process_msg_files.py", line 30, in extract_msg_file
    attachment.save(customPath=output_path)
  File "/home/user/project/.venv/lib/python3.9/site-packages/extract_msg/attachment.py", line 232, in save
    if createdZip:
UnboundLocalError: local variable 'createdZip' referenced before assignment
```

**Additional context**

A similar pattern exists in `message_base.py` and `signed_attachment.py`

**Comment by TheElementalOfDestruction** [comment]
Actually that's a bug in the unreleased version, lol, but I'll fix that real quick. I was wondering why I had a redundant check, but now I know

**Comment by programmarchy** [comment]
Ah okay. When I was testing for #321 I was probably seeing other work that's not done yet.

I also found an issue with `headerFormatProperties` in `contact.py`:

https://github.com/programmarchy/msg-extractor/commit/4950a3a6508e91c03fcbba9103798f7625cfed86

Are you still working on this also or would you want me to create an issue + PR?

**Comment by TheElementalOfDestruction** [comment]
No such issue should be present with signed attachment (it has the proper check of `if _zip and createdZip`. `_zip` being set means `createdZip` will be set. This is now fixed.

**Comment by TheElementalOfDestruction** [comment]
> Ah okay. When I was testing for #321 I was probably seeing other work that's not done yet.
> 
> I also found an issue with `headerFormatProperties` in `contact.py`:
> 
> [programmarchy@4950a3a](https://github.com/programmarchy/msg-extractor/commit/4950a3a6508e91c03fcbba9103798f7625cfed86)
> 
> Are you still working on this also or would you want me to create an issue + PR?

This needs an issue and pr
