### ISSUE TITLE
nit: minor typo in logger warning message

### ISSUE THREAD

**Issue by dobizz** [TeamMsgExtractor/msg-extractor#333]
Been seeing this in my code and traced it back to be coming from this package.

https://github.com/TeamMsgExtractor/msg-extractor/blob/ab7618c4da4a4090ddb09e8246af179baaa29e03/extract_msg/attachment.py#L40

**Comment by TheElementalOfDestruction** [comment]
Alright, I've fixed the typo in the next-release branch so it will be included in the next version of the module.

Do note that if you are seeing that warning it is probably not a good sign for the files you are trying to work with, as they aren't following the standards as well as they probably should be. However, if you are *only* getting the warning and not getting exceptions, then you *can* safely ignore it. See #318 for details on why the warning exists.

**Comment by dobizz** [comment]
> Alright, I've fixed the typo in the next-release branch so it will be included in the next version of the module.
> 
> Do note that if you are seeing that warning it is probably not a good sign for the files you are trying to work with, as they aren't following the standards as well as they probably should be. However, if you are _only_ getting the warning and not getting exceptions, then you _can_ safely ignore it. See #318 for details on why the warning exists.

Thank you. Just saw it after updating to the latest version, was using `v0.36` for quite a while and updated to `v0.39` along with other packages I was using and saw that it came from this one. No exceptions though,  I was just wondering where did all these warnings come from, based on the link you provided I guess it is with those nested emails they send.
