### ISSUE TITLE
Sub-mail in the msg file

### ISSUE THREAD

**Issue by JONGSKY** [TeamMsgExtractor/msg-extractor#358]
Thank you for making a good module.
As I use the module, I have a question and leave an issue.

There are usually mails sent and received several times in the msg file. 
So there are several sub-mails in the msg file.

So I was wondering if there is a way to receive submessages on the Message object or on another object.

Thank you.

**Comment by TheElementalOfDestruction** [comment]
I'm not sure I understand the question, but if you add an MSG file as an attachment then it's accessible as an attachment when you open it in the module. The only exception is if it's attached as a web attachment which isn't yet supported by the module. There is no need to "receive" it if it's been attached normal.

**Comment by JONGSKY** [comment]
What I'm trying to say is the following form of mail.

---------------------------
From : ~~
Sent : ~~
To : ~~
Cc : ~~
Subject : ~~

Hi my name is jongsky

From : ~~
Sent : ~~
To : ~~
Cc : ~~
Subject : ~~

Hello, Jong Sky. My name is Tom. Nice to meet you.

From : ~~
Sent : ~~
To : ~~
Cc : ~~
Subject : ~~

Tom, what are you doing this weekend
---------------------------

If there is this type of mail, it consists of one text, "Hi my name to this week", and I wonder if I can separate the submessages in the msg file.

**Comment by TheElementalOfDestruction** [comment]
Ah, I see what you mean. In the msg file, these bodies are all stored together as a single body with no guaranteed way to identify separation. As such, it is beyond the scope of this project to try and separate them. If you want to do this, you'll likely need some kind of code that can do complex text analysis.
