### ISSUE TITLE
Cannot decode using CP950 (and possibly others) due to the Python implementation differing from the Microsoft implementation

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [TeamMsgExtractor/msg-extractor#373]
Microsoft's implementation of CP950 has a large portion of the user-defined characters area filled. As these characters are not universal to the encoding, Python's implementation does not accept them when encoding or decoding data, which can lead to encoding issues (this is apparent with `RTFDE` failing to decode some data using CP950.

A fix is to create the `encoding` submodule which handles a number of jobs related to encodings, including implementing the Microsoft versions should they be unavailable or differ from the Python implementation.

Version 0.42.0, currently available for preview on the next-release branch, will definitively have support for the plain text body using CP950, as I have implemented code to handle decoding and encoding. If I discover other encodings that differ from the Python implementation, I plan to add them to that release as well and will note them here. Most encodings added will likely only find use on significantly older MSG files, if they find any use at all. However, I decided it would be better to have support for them and not need it rather than not have support and end up needing it.

**Comment by TheElementalOfDestruction** [comment]
Support for windows-874, one of the codecs that had no support at all, has been added to the next-release branch and as such will be in version 0.42.0. Of course, you may need to verify it's validity, as I cannot confirm test files will decode correctly, however I have implemented it from information I found on it so it should be accurate.

**Comment by TheElementalOfDestruction** [comment]
Support for the following codecs (using the names that Microsoft uses in its code page map) will also be included:
* x-mac-ce
* x-mac-cyrillic
* x-mac-greek
* x-mac-icelandic
* x-mac-turkish

**Comment by TheElementalOfDestruction** [comment]
All of the listed encodings have been implemented and should not cause issues. If you are still getting a CP950 error, check to see if it is coming from `RTFDE`. If it is, you can see the relevant issue [here](https://github.com/seamustuohy/RTFDE/issues/19) and add that you would like to see support implemented there.

**Comment by gwiedeman** [comment]
I'm still having this issue, and I don't believe that the .msg I'm working with is cp950. If I'm wrong or misunderstanding, please feel free to close again.

In python 3.11,
```
mail = extract_msg.openMsg(path)
if mail.htmlBody
```
raises:
```
Traceback (most recent call last):
  File "/mailbagit/test.py", line 21, in <module>
    if (mail.htmlBody):
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/extract_msg/msg_classes/message_base.py", line 1130, in htmlBody
    htmlBody = self.deencapsulateBody(self.rtfBody, DeencapType.HTML)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/extract_msg/msg_classes/message_base.py", line 226, in deencapsulateBody
    if self.deencapsulatedRtf and self.deencapsulatedRtf.content_type == 'html':
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/extract_msg/msg_classes/message_base.py", line 977, in deencapsulatedRtf
    deencapsultor.deencapsulate()
  File "/usr/local/lib/python3.11/site-packages/RTFDE/deencapsulate.py", line 119, in deencapsulate
    Decoder.update_children(self.full_tree)
  File "/usr/local/lib/python3.11/site-packages/RTFDE/text_extraction.py", line 671, in update_children
    obj.children = [i for i in self.iterate_on_children(children)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RTFDE/text_extraction.py", line 671, in <listcomp>
    obj.children = [i for i in self.iterate_on_children(children)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RTFDE/text_extraction.py", line 744, in iterate_on_children
    item.children = [i for i in self.iterate_on_children(item.children)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RTFDE/text_extraction.py", line 744, in <listcomp>
    item.children = [i for i in self.iterate_on_children(item.children)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RTFDE/text_extraction.py", line 744, in iterate_on_children
    item.children = [i for i in self.iterate_on_children(item.children)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RTFDE/text_extraction.py", line 744, in <listcomp>
    item.children = [i for i in self.iterate_on_children(item.children)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RTFDE/text_extraction.py", line 731, in iterate_on_children
    decoded_hex = decode_hex_char(base_bytes, current_codec)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RTFDE/text_extraction.py", line 623, in decode_hex_char
    decoded = item.decode(codec)
              ^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'cp950' codec can't decode byte 0x83 in position 0: illegal multibyte sequence
```

In `extract_msg==0.41.5`, `mail.htmlBody` is returning `True`, but it looks like its returning ascii text when there is a HTML body when viewed in Outlook.

If `extract_msg` in unable to extract HTML because of the dependancy issue, I wouldn't expect `mail.htmlBody` to just fail, I don't think. Maybe I'd expect it to return an empty string or something, but I'm not sure. Happy to share the .msg examples I'm working with if that helps.

Relatedly, does `extract_msg` expose the encoding needed to `mail.htmlBody.decode()`?

Thanks for maintaining!

**Comment by TheElementalOfDestruction** [comment]
@gwiedeman This is an issue with `RTFDE`, not `extract-msg`. A similar issue was opened there https://github.com/seamustuohy/RTFDE/issues/19 and I'd recommend you go and leave feedback that you need it to be fixed as well. Previously I was the only user who it affected that reported issues.

Version 0.41.5 of `extract-msg` used a previous version of `RTFDE` which had *numerous* issues, and I don't believe it was actually able to process the CP950 codec, even if it may have not thrown an issue about it. Version 0.42 and above use version 0.1.0 of `RTFDE`. It's actually possible to get `RTFDE` to support CP950 by overriding it's encoding detection to return the encoding name used by `extract-msg` (windows-950). This was not included in `extract-msg` due to the method being rather hacky. You can look at the issue and the pull request made (which was undone) to see how the change can be made to add support.

As for expecting it to fail on a dependency issue, the problem is that can easily hide issues with the dependency and cause them to never get reported (something I want to avoid). *However*, I acknowledge that it's a legitimate use case, and so a feature has been provided to allow the user to ignore certain types of issues. This can be done by using the optional `errorBehavior` keyword to `openMsg`. It should be given an instance of `extract_msg.enums.ErrorBehavior`, which is an `IntFlag` that specifies what types of errors should be silenced. The option you are looking for is `ErrorBehavior.RTFDE` which will just suppress any errors at all. If you just want to ignore encoding errors like that and keep errors about the RTF data being malformed, you can use `ErrorBehavior.RTFDE_UNKNOWN_ERROR` instead.

Finally, the encoding for the HTML body would just be whatever the HTML body specifies (or *should* be). Something like `bs4` can probably be used to find that, but `chardet` would be a good method of determining the encoding.

**Comment by gwiedeman** [comment]
Okay, I did leave [a comment there](https://github.com/seamustuohy/RTFDE/issues/19#issuecomment-1813029768) documenting what appears to be an encoding error that's also being handled weird.

`chardet` isn't great for individual messages, as it doesn't seem like there is enough text to correctly get the encoding in many cases. Is the encoding explicitly listed in the .msg files some way? That might be able to help sorting out these issues. In this case the encoding seems to be listed in the RTF, so maybe that's a potential role for the dependency per my comment. Thanks!

**Comment by TheElementalOfDestruction** [comment]
The encoding listed in msg files is for the string properties, an encoding that does not apply to the HTML body. As far as I know, there are not any listed properties designed to specify the encoding outside of what the HTML body specified. Whatever encoding is listed in the RTF body is specifically for the RTF and does not necessarily apply to the HTML body.
