### ISSUE TITLE
Not able to use --extract-embedded flag in python API

### ISSUE THREAD

**Issue by MugdhaHardikar-GSLab** [TeamMsgExtractor/msg-extractor#386]
I dont want the ".msg" attachments to be recursively extracted. Want them to save as ".msg" files itself.
I the [documentation](https://pypi.org/project/extract-msg/) of 0.45.0 version, I found the flag "--extract-embedded " which works exactly as expected on command line.
But when I am using python API I am always getting the folder instead of .msg file.
Here is my sample snippet:

  msg = extract_msg.Message(msg_file)
  
  attachments = msg.attachments
  
  for attachment in attachments:
  
      output_filename = attachment.getFilename()
  
      attachment.save(customPath="/home/mugdha/temp", customFilename="attach.msg")

I am hoping that I should be able to specify the flag at line 1 when i create the Message instance. I tried to provide options like bellow but none of them worked.

`
msg = extract_msg.Message(msg_file, extract_embedded=True)

msg = extract_msg.Message(msg_file, extractEmbedded=True)
`

Any help in this regard will be highly appreciated. 

Thanks

**Comment by TheElementalOfDestruction** [comment]
The option `extractEmbedded` (I need to figure out a good way to move the wiki pages over to read the docs, but I don't fully understand how to work with RTD) is for the save method, not the open method.

Additionally, it's generally recommended to use `openMsg` instead of `Message` directly for opening the file to properly handle msg files not being Message instances.

**Comment by TheElementalOfDestruction** [comment]
Additionally, inspection of `__main__.py` should help show the translation of the different options on the command line to where they are used by the API.

**Comment by MugdhaHardikar-GSLab** [comment]
Thanks a lot for the quick reply. It solved my problem. 
Here is my working snippet:

msg = extract_msg.openMsg(
    msg_file,
)
attachments = msg.attachments
for attachment in attachments:
    output_filename = attachment.getFilename()
    print(output_filename)
    attachment.save(
        customPath="/home/mugdha/temp",
        customFilename="attach-2.msg",
        extractEmbedded=True,
    )
