### ISSUE TITLE
Extract conversation from .msg file 

### ISSUE THREAD

**Issue by Raphenri09** [TeamMsgExtractor/msg-extractor#402]
I have a .msg file with multiple replies in it (conversation between two persons). What is the best way to extract each reply with the info (date, send to, etc.) ?
So far I could just extract the whole conversation as one msg.body and it is not really what I need. 
Thanks for your help

**Comment by TheElementalOfDestruction** [comment]
Unfortunately, reply data like that is not kept separated in any way in the msg file, so you either need a copy of each individual message or need to try and do some analysis to determine which part of the body is what reply
