### ISSUE TITLE
SignedAttachment missing private method `_handleFnc`

### ISSUE THREAD

**Issue by mescanne** [TeamMsgExtractor/msg-extractor#409]
**Bug Metadata**
* Version of extract_msg: 0.48.2
* Your python version: Python 3.11
* How did you launch extract_msg?
  - [x] I used the extract_msg package

**Describe the bug**

Exception with signed_att.py looking for _handleFnc:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".cache/pypoetry/virtualenvs/docai-NS_TRTt_-py3.11/lib/python3.11/site-packages/extract_msg/msg_classes/message_base.py", line 899, in <listcomp>
    attachmentReturns = [attachment.save(**kwargs) for attachment in self.attachments if not (skipHidden and attachment.hidden)]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".cache/pypoetry/virtualenvs/docai-NS_TRTt_-py3.11/lib/python3.11/site-packages/extract_msg/attachments/signed_att.py", line 138, in save
    fullFilename = self._handleFnc(_zip, filename, customPath, kwargs)
                   ^^^^^^^^^^^^^^^

**Additional context**
Happy to share code that resulted in this. This looks fairly straightforward. I'm not sure the best approach for resolving.

Thanks,
Mark

**Comment by TheElementalOfDestruction** [comment]
It not being a subclass is very intentional, but it missing that function is not. Whoops. Give me a few minutes and I'll have a correction out

**Comment by TheElementalOfDestruction** [comment]
The private method has been added in version 0.48.3. Let me know if you have any more issues.

**Comment by mescanne** [comment]
Thanks a lot!
