### ISSUE TITLE
Spelling error in message_signed_base

### ISSUE THREAD

**Issue by jcmmagnusson** [TeamMsgExtractor/msg-extractor#414]
**Bug Metadata**
* Version of extract_msg: 0.48.4
* Your python version: Python 3.11
* How did you launch extract_msg?
  - [x] I used the extract_msg package

**Describe the bug**
On line 133 in `message_signed_base.py` there is a typo ("html.escpae") that is causing an error when reaching this code path.

**Comment by TheElementalOfDestruction** [comment]
Fixed in version 0.48.5. Thanks.
