### ISSUE TITLE
Corrupt MSG cannot close after error. 

### ISSUE THREAD

**Issue by ragebear00** [TeamMsgExtractor/msg-extractor#417]
**Bug Metadata**
* Version of extract_msg: 0.48.5
* Your python version: Python [3.10]
* How did you launch extract_msg?
I used the extract_msg package

**Describe the bug**
If the “msg” is corrupt and extract_msg.openMsg(filename) will fail, BUT file will not close() after the error. Python will keep the file open until the process is closed.

**Additional context**
Just add “self.close(“) in \extract_msg\msg_classes\msg.py before “raise StandardViolationError('File does not contain a property stream.') from None” can solve the issue.

**Comment by TheElementalOfDestruction** [comment]
Can you please give a full traceback to show what part of the __init__ method the error occurs in? The design means it should be closing the file already if an error occurs

**Comment by ragebear00** [comment]
The code is
`def msgTest(filename):
    nAttachment = 0
    try:
        msg = extract_msg.openMsg(filename)      #filename including path
        msg.saveAttachments(customPath=r'C:\_a')
    except Exception as e:
        print(e)
        os.remove(filename)`

Error
![Error](https://github.com/TeamMsgExtractor/msg-extractor/assets/168278723/70ea5fc7-e93a-464a-b426-6bb235bd2e6e)

**Comment by TheElementalOfDestruction** [comment]
Ah, I see the problem. Turns out that the file opens completely in openMsg but then doesn't have protections there to force it to close if an issue occurs, and apparently the check for a properties stream doesn't happen in __init__. I'll deal with this when I have the energy, as I'm currently recovering from a surgery. Hopefully it will be later today.

**Comment by ragebear00** [comment]
Wish you recover soon! The temp solution works anyway.

**Comment by TheElementalOfDestruction** [comment]
Thank you for your well wishes. 

Can you see if the code on #next-release solves your issues?

**Comment by ragebear00** [comment]
Tested and the bug fixed in the #next release

**Comment by TheElementalOfDestruction** [comment]
Thanks, I've pushed the fix in version 0.48.6
