### ISSUE TITLE
Typo in open_msg.py

### ISSUE THREAD

**Issue by itoso** [TeamMsgExtractor/msg-extractor#420]
* Version of extract_msg: [0.48.6]
* Your python version: Python [3.10.11]
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
Opening a msg file fails immediately.

```
msg = extract_msg.openMsg("./input/example.msg")
```

There seems a typo in open_msg.py", line 110.

**Comment by TheElementalOfDestruction** [comment]
Thanks. Forgot to run tests on normal files and I assume the check that was performed was only on the bad files I was fixing an issue for on the last version. This has been fixed in the most recent version
