### ISSUE TITLE
ReadMe update

### ISSUE THREAD

**Issue by ragebear00** [TeamMsgExtractor/msg-extractor#426]
It would be great to include samples to use those switch/option in the python code in https://github.com/TeamMsgExtractor/msg-extractor/wiki/Using-msg-extractor-In-Your-Own-Code

msg.open(f, errorBehavior = extract_msg.enums.ErrorBehavior.ATTACH_NOT_IMPLEMENTED)
msg.saveAttachments(customPath=r'C:\', extractEmbedded=True)

msg = extract_msg.openMsg(filename, skip-body-not-found=True, skip-not-implemented=True) ?

usage: extract_msg [-h] [--use-content-id] [--json] [--file-logging] [-v] [--log LOG] [--config CONFIGPATH] [--out OUTPATH] [--use-filename] [--dump-stdout] [--html] [--pdf] [--wk-path WKPATH] [--wk-options [WKOPTIONS ...]]
                   [--prepared-html] [--charset CHARSET] [--raw] [--rtf] [--allow-fallback] [--skip-body-not-found] [--zip ZIP] [--save-header] [--attachments-only] [--skip-hidden] [--no-folders] [--skip-embedded] [--extract-embedded]
                   [--overwrite-existing] [--skip-not-implemented] [--out-name OUTNAME | --glob] [--ignore-rtfde] [--progress] [-s]
                   msg [msg ...]

**Comment by ragebear00** [comment]
I will edit the wiki page directly, if any example to share

**Comment by TheElementalOfDestruction** [comment]
The wiki pages are being transferred over as much as possible to the ReadTheDics site, the contents of which is stored in the documentation branch. You can pull request to that for changes to the wiki pages. Additionally, the readme can be changed by pull requesting to next release.

If you look at `__main__.py` you can see some of the argument translation with the rest being in `utils.py` in the `getCommandArgs` function
