### ISSUE TITLE
The latest release, v0.50.0, is unexpectedly causing issues and breaking functionality.

### ISSUE THREAD

**Issue by arindam987** [TeamMsgExtractor/msg-extractor#434]
While working on an integration that used the extract-msg package, which had previously been working fine, it suddenly started failing with the following error message:

BUG
The latest release is causing the following error:
venv/lib/python3.9/site-packages/extract_msg/msg_classes/calendar_base.py:15: in <module>
    from .message_base import MessageBase
E     File "/opt/atlassian/pipelines/agent/build/venv/lib/python3.9/site-packages/extract_msg/msg_classes/message_base.py", line 1216
E       formatter = (lambda name, value: f'<b>{name}:</b>&nbsp;{inputToString(htmlSanitize(value), self.stringEncoding).encode('ascii', 'xmlcharrefreplace').decode()}')
E                                                                                                                               ^
E   SyntaxError: f-string: unmatched '('

Upon further investigation, I found that the issue began with the latest release, version 0.50.0.

**Comment by JoanSForgeFlow** [comment]
We are having the same issue! :+1:

**Comment by MatteoCampinoti94** [comment]
We encountered the exact same error.

It is because that f-string is formatted per Python 3.12 specs, it is not compatible with Python < 3.12.

Specifically, Python 3.12 allows to use the same quotes that contain the f-string inside the the various substitutions, e.g., `f"Hello {"world!"}"`. That is not allowed in previous versions of Python and the parser splits that f-string into multiple substrings with statements in between them, which is obviously erroneous, hence the `SyntaxError`.

**Comment by MatteoCampinoti94** [comment]
@arindam987 I suggest changing the title of the issue to reflect the underlining error.

**Comment by TheElementalOfDestruction** [comment]
This is what happens when I push a release while tired. I forgot to run the tests on the code. I really need to figure out how to make it so they tests autorun before I can even merge a pull request. I'll push a fix to this as soon as possible

**Comment by MatteoCampinoti94** [comment]
> This is what happens when I push a release while tired. I forgot to run the tests on the code. I really need to figure out how to make it so they tests autorun before I can even merge a pull request. I'll push a fix to this as soon as possible

You can sent your pull request to not be mergeable until all tests have run without errors :)

You can do it under Settings -> Branches.

**Comment by TheElementalOfDestruction** [comment]
BTW this wasn't even an issue with using python 3.12 formatting, I just was tired enough to not notice I was in an f string for the part of the code I was looking at and went "why is this inconsistent?" and changed it without waiting to see if it would note an issue with that change.

> You can sent your pull request to not be mergeable until all tests have run without errors :)
> 
> You can do it under Settings -> Branches.

I'm not sure what setting that would actually be, none of the setting there mention tests

**Comment by MatteoCampinoti94** [comment]
Thanks for the quick patch! We'll add it to our repository!

**Comment by MatteoCampinoti94** [comment]
> I've found the setting being talked about now to prevent a pull request merge until tests pass, I just need to figure out how to set it up so that github knows what the tests are

You can set GitHub actions for PRs and merging, and the PR will automatically wait for all tests running on its commits before allowing a merge.

**Comment by CalMckenzie** [comment]
Just want to say thanks for resolving this so quickly - by the time I'd encountered the bug today, it was about 15 minutes before the 50.1 release. Awesome!

**Comment by TheElementalOfDestruction** [comment]
I fixed it right after I woke up :joy:

I seem to have gotten the tests to run, but can't quite figure out how to get them to register as a check. I'm the only one approving pull requests right now though, so I can just manually wait to see the status and decide what to do if I can't get that figured out
