### ISSUE TITLE
When using msg.htmlBody, the time is too long

### ISSUE THREAD

**Issue by MaskInLife** [TeamMsgExtractor/msg-extractor#445]
- When the **email is complex** (e.g., with multiple tables), `msg.htmlBody` takes longer to load: when there are three tables with 4 or 5 rows, it takes more than 20 seconds.
- It seems that the deencapsulateBody method, which converts rtfBody to HTML, takes more time.
- Is there a way to optimize the parsing time? 😥

**Comment by TheElementalOfDestruction** [comment]
Not from extract-msg. The amount of time taken depends entirely on the efficiency of the RTFDE module

**Comment by MaskInLife** [comment]
> If you are dissatisfied by the amount of time RTFDE takes, you can try to create an issue on the GitHub here: https://github.com/seamustuohy/RTFDE
> 
> I suspect much of the issue you are experiencing comes from the embedded groups that tables cause in the RTF stream, which causes deep recursion in RTFDE.

OK, thanks! I saw that the actual parsing of htmlBody is RTFDE.DeEncapsulator, I will go to ask about it, thanks again!❤
