### ISSUE TITLE
How can I save attached file in msg?

### ISSUE THREAD

**Issue by Yuwenqing** [TeamMsgExtractor/msg-extractor#88]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* - [x] Using latest supported version of extract_msg
* Your python version: Python [2.7 | 3.6.7]
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
[put your code here]
```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
[Put your traceback here]
```

**Screenshots**
[Insert any screenshots or debug pictures here]

**Additional context**
[Add any other context about the problem here.]

**Comment by TheElementalOfCreation** [comment]
use `Attachment.save` . For example you could do something like this:
```python
for x in msg_file.attachments:
    x.save()
```

**Comment by KelumPerera** [comment]
> 
> 
> use `Attachment.save` . For example you could do something like this:
> 
> ```python
> for x in msg_file.attachments:
>     x.save()
> ```

Dear Sir, 
1. I like to get attachment names into a python list. Appreciate it if you can tell how to do this using this python library.
2. Also, if possible can you guide how to get a list of attachment names, when using win32.client method.

import win32com.client

outlook=win32com.client.Dispatch("Outlook.Application").GetNamespace("MAPI")
msg=outlook.OpenSharedItem(r'''C:\Users\Win10\Desktop\outlookfile.msg''')

msg_AttachmentsList = msg.PropertyAccessor.GetProperty("http://schemas.microsoft.com/mapi/proptag/0x0E1B000B") # Only get True if there is an attachment

**Comment by TheElementalOfCreation** [comment]
@KelumPerera Unfortunately I do not know how to use the win32 library, but if you want to names of the attachments, you can do this:
```python
import extract_msg

msg = extract_msg.Message("path/to/msgfile.msg")

longFileNames = [x.longFilename for x in msg.attachments] # This is probably the one you want

shortFileNames = [x.shortFilename for x in msg.attachments]

**Comment by MuseHorizon** [comment]
Thanks I appreciate the help.
I would suggest adding the below to the README as this would a common use for this library.
```python
for x in msg_file.attachments:
    x.save()
```

**Comment by TheElementalOfDestruction** [comment]
I'll work on getting so kind of help for saving attachments done soon.

**Comment by TheElementalOfDestruction** [comment]
Don't know why this was left open, but I'm guessing it's because I was mixing this issue up with another. Documentation is all being bundled into the issues involving finishing up the README and the wiki.
